<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jiale SO">
<meta name="dcterms.date" content="2024-09-14">

<title>IS415-GAA: JialeSo - Spatial Weights and Applications</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">IS415-GAA: JialeSo</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-fas fa-laptop-code" role="img">
</i> 
 <span class="menu-text">Hands-On Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../../Hands_On_exercises/Hands_On_Exercise_1/Hands_On_Exercise1.html"><i class="bi bi-fas fa-code" role="img">
</i> 
 <span class="dropdown-text">Hands-On Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands_On_exercises/Hands_On_Exercise_2/Hands_On_Exercise2.html"><i class="bi bi-fas fa-code" role="img">
</i> 
 <span class="dropdown-text">Hands-On Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands_On_exercises/Hands_On_Exercise_3/Hands_On_Exercise3.html"><i class="bi bi-fas fa-code" role="img">
</i> 
 <span class="dropdown-text">Hands-On Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands_On_exercises/Hands_On_Exercise_4/Hands_On_Exercise4.html"><i class="bi bi-fas fa-code" role="img">
</i> 
 <span class="dropdown-text">Hands-On Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands_On_exercises/Hands_On_Exercise_5/Hands_On_Exercise5.html"><i class="bi bi-fas fa-code" role="img">
</i> 
 <span class="dropdown-text">Hands-On Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../404.html"><i class="bi bi-fas fa-code" role="img">
</i> 
 <span class="dropdown-text">Hands-On Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../404.html"><i class="bi bi-fas fa-code" role="img">
</i> 
 <span class="dropdown-text">Hands-On Exercise 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../404.html"><i class="bi bi-fas fa-code" role="img">
</i> 
 <span class="dropdown-text">Hands-On Exercise 8</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../404.html"><i class="bi bi-fas fa-code" role="img">
</i> 
 <span class="dropdown-text">Hands-On Exercise 9</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../404.html"><i class="bi bi-fas fa-code" role="img">
</i> 
 <span class="dropdown-text">Hands-On Exercise 10</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../404.html"><i class="bi bi-fas fa-code" role="img">
</i> 
 <span class="dropdown-text">Hands-On Exercise 11</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../404.html"><i class="bi bi-fas fa-code" role="img">
</i> 
 <span class="dropdown-text">Hands-On Exercise 12</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../404.html"><i class="bi bi-fas fa-code" role="img">
</i> 
 <span class="dropdown-text">Hands-On Exercise 13</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-fas fa-chalkboard-teacher" role="img">
</i> 
 <span class="menu-text">In-Class Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../../In_Class_exercises/In_Class_Exercise_1/In_Class_Exercise1.html"><i class="bi bi-fas fa-file-alt" role="img">
</i> 
 <span class="dropdown-text">In-Class Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In_Class_exercises/In_Class_Exercise_2/In_Class_Exercise2.html"><i class="bi bi-fas fa-file-alt" role="img">
</i> 
 <span class="dropdown-text">In-Class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In_Class_exercises/In_Class_Exercise_3/In_Class_Exercise3.html"><i class="bi bi-fas fa-file-alt" role="img">
</i> 
 <span class="dropdown-text">In-Class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In_Class_exercises/In_Class_Exercise_4/In_Class_Exercise4.html"><i class="bi bi-fas fa-file-alt" role="img">
</i> 
 <span class="dropdown-text">In-Class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In_Class_exercises/In_Class_Exercise_5/In_Class_Exercise5.html"><i class="bi bi-fas fa-file-alt" role="img">
</i> 
 <span class="dropdown-text">In-Class Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../404.html"><i class="bi bi-fas fa-file-alt" role="img">
</i> 
 <span class="dropdown-text">In-Class Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../404.html"><i class="bi bi-fas fa-file-alt" role="img">
</i> 
 <span class="dropdown-text">In-Class Exercise 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../404.html"><i class="bi bi-fas fa-file-alt" role="img">
</i> 
 <span class="dropdown-text">In-Class Exercise 8</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../404.html"><i class="bi bi-fas fa-file-alt" role="img">
</i> 
 <span class="dropdown-text">In-Class Exercise 9</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../404.html"><i class="bi bi-fas fa-file-alt" role="img">
</i> 
 <span class="dropdown-text">In-Class Exercise 10</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../404.html"><i class="bi bi-fas fa-file-alt" role="img">
</i> 
 <span class="dropdown-text">In-Class Exercise 11</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../404.html"><i class="bi bi-fas fa-file-alt" role="img">
</i> 
 <span class="dropdown-text">In-Class Exercise 12</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../404.html"><i class="bi bi-fas fa-file-alt" role="img">
</i> 
 <span class="dropdown-text">In-Class Exercise 13</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-fas fa-home" role="img">
</i> 
 <span class="menu-text">Take-Home Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li>
    <a class="dropdown-item" href="../../Take_Home_Exercises/Take_Home_Exercise_1/Take_Home_Exercise1.html"><i class="bi bi-fas fa-file-alt" role="img">
</i> 
 <span class="dropdown-text">Take-Home Exercise 1</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> <i class="bi bi-fas fa-home" role="img">
</i> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../404.html"> <i class="bi bi-fas fa-info-circle" role="img">
</i> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#outcome-of-this-exercise" id="toc-outcome-of-this-exercise" class="nav-link active" data-scroll-target="#outcome-of-this-exercise">Outcome of this Exercise</a></li>
  <li><a href="#setting-the-environment" id="toc-setting-the-environment" class="nav-link" data-scroll-target="#setting-the-environment">1.0 Setting the Environment</a></li>
  <li><a href="#importing-the-data" id="toc-importing-the-data" class="nav-link" data-scroll-target="#importing-the-data">2.0 Importing the data</a></li>
  <li><a href="#visualising-regional-development-indicator" id="toc-visualising-regional-development-indicator" class="nav-link" data-scroll-target="#visualising-regional-development-indicator"><strong>3.0 Visualising Regional Development Indicator</strong></a></li>
  <li><a href="#computing-contiguity-spatial-weights" id="toc-computing-contiguity-spatial-weights" class="nav-link" data-scroll-target="#computing-contiguity-spatial-weights"><strong>4.0 Computing Contiguity Spatial Weights</strong></a>
  <ul class="collapse">
  <li><a href="#computing-queen-contiguity-based-neighbours" id="toc-computing-queen-contiguity-based-neighbours" class="nav-link" data-scroll-target="#computing-queen-contiguity-based-neighbours">4.1 <strong>Computing (QUEEN) contiguity based neighbours</strong></a></li>
  <li><a href="#creating-rook-contiguity-based-neighbours" id="toc-creating-rook-contiguity-based-neighbours" class="nav-link" data-scroll-target="#creating-rook-contiguity-based-neighbours">4.2 <strong>Creating (ROOK) contiguity based neighbours</strong></a></li>
  <li><a href="#visualizing-contiguity-weights" id="toc-visualizing-contiguity-weights" class="nav-link" data-scroll-target="#visualizing-contiguity-weights">4.3 Visualizing Contiguity Weights</a>
  <ul class="collapse">
  <li><a href="#plotting-contiguity-based-neighbours-map" id="toc-plotting-contiguity-based-neighbours-map" class="nav-link" data-scroll-target="#plotting-contiguity-based-neighbours-map">4.3.1 Plotting Contiguity based Neighbours Map</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#computing-distance-based-neighbors" id="toc-computing-distance-based-neighbors" class="nav-link" data-scroll-target="#computing-distance-based-neighbors">5.0 Computing Distance Based Neighbors</a>
  <ul class="collapse">
  <li><a href="#key-steps" id="toc-key-steps" class="nav-link" data-scroll-target="#key-steps">Key Steps:</a></li>
  <li><a href="#determine-cut-off-distance" id="toc-determine-cut-off-distance" class="nav-link" data-scroll-target="#determine-cut-off-distance">5.1 Determine Cut-Off Distance</a></li>
  <li><a href="#computing-fixed-and-adaptive-distance-weight-matrix" id="toc-computing-fixed-and-adaptive-distance-weight-matrix" class="nav-link" data-scroll-target="#computing-fixed-and-adaptive-distance-weight-matrix">5.2 Computing Fixed and Adaptive Distance Weight Matrix</a></li>
  </ul></li>
  <li><a href="#weight-based-on-in-versed-distance-method." id="toc-weight-based-on-in-versed-distance-method." class="nav-link" data-scroll-target="#weight-based-on-in-versed-distance-method.">6.0 Weight Based on In-versed Distance Method.</a></li>
  <li><a href="#row-standardized-weight-matrix" id="toc-row-standardized-weight-matrix" class="nav-link" data-scroll-target="#row-standardized-weight-matrix">7.0 Row-standardized Weight Matrix</a>
  <ul class="collapse">
  <li><a href="#key-concepts" id="toc-key-concepts" class="nav-link" data-scroll-target="#key-concepts">Key Concepts:</a></li>
  </ul></li>
  <li><a href="#application-of-spatial-weight-matrix" id="toc-application-of-spatial-weight-matrix" class="nav-link" data-scroll-target="#application-of-spatial-weight-matrix">8.0 <strong>Application of Spatial Weight Matrix</strong></a>
  <ul class="collapse">
  <li><a href="#spatial-lag-with-row-standardized-weights" id="toc-spatial-lag-with-row-standardized-weights" class="nav-link" data-scroll-target="#spatial-lag-with-row-standardized-weights">8.1 spatial lag with row-standardized weights</a></li>
  <li><a href="#spatial-lag-as-a-sum-of-neighbouring-values" id="toc-spatial-lag-as-a-sum-of-neighbouring-values" class="nav-link" data-scroll-target="#spatial-lag-as-a-sum-of-neighbouring-values">8.2 spatial lag as a sum of neighbouring values</a></li>
  <li><a href="#spatial-window-average" id="toc-spatial-window-average" class="nav-link" data-scroll-target="#spatial-window-average">8.3 spatial window average</a>
  <ul class="collapse">
  <li><a href="#include-self-in-neighbor-list" id="toc-include-self-in-neighbor-list" class="nav-link" data-scroll-target="#include-self-in-neighbor-list">8.3.1. <strong>Include Self in Neighbor List</strong>:</a></li>
  <li><a href="#convert-to-weights-list" id="toc-convert-to-weights-list" class="nav-link" data-scroll-target="#convert-to-weights-list">8.3.2. <strong>Convert to Weights List</strong>:</a></li>
  <li><a href="#calculate-spatial-lag-with-self" id="toc-calculate-spatial-lag-with-self" class="nav-link" data-scroll-target="#calculate-spatial-lag-with-self">8.3.3 <strong>Calculate Spatial Lag (with Self)</strong>:</a></li>
  <li><a href="#store-results-and-modify-data" id="toc-store-results-and-modify-data" class="nav-link" data-scroll-target="#store-results-and-modify-data">8.3.4. <strong>Store Results and Modify Data</strong>:</a></li>
  <li><a href="#visualize-the-results-and-interpret" id="toc-visualize-the-results-and-interpret" class="nav-link" data-scroll-target="#visualize-the-results-and-interpret"><strong>8.3.5 Visualize the Results</strong>: and Interpret</a></li>
  </ul></li>
  <li><a href="#spatial-window-sum" id="toc-spatial-window-sum" class="nav-link" data-scroll-target="#spatial-window-sum">8.4 spatial window sum</a>
  <ul class="collapse">
  <li><a href="#add-diagonal-element-include-self-as-neighbor" id="toc-add-diagonal-element-include-self-as-neighbor" class="nav-link" data-scroll-target="#add-diagonal-element-include-self-as-neighbor">8.4.1 <strong>Add Diagonal Element (Include Self as Neighbor)</strong>:</a></li>
  <li><a href="#create-binary-weights-convert-neighbor-to-weight-matrix" id="toc-create-binary-weights-convert-neighbor-to-weight-matrix" class="nav-link" data-scroll-target="#create-binary-weights-convert-neighbor-to-weight-matrix">8.4.2 <strong>Create Binary Weights</strong>: &amp; Convert Neighbor to weight matrix</a></li>
  <li><a href="#calculate-spatial-window-sum-for-gdppc" id="toc-calculate-spatial-window-sum-for-gdppc" class="nav-link" data-scroll-target="#calculate-spatial-window-sum-for-gdppc">8.4.3 <strong>Calculate Spatial Window Sum for GDPPC</strong>:</a></li>
  <li><a href="#visualise-and-interpret-the-results" id="toc-visualise-and-interpret-the-results" class="nav-link" data-scroll-target="#visualise-and-interpret-the-results">8.4.4 visualise and interpret the results</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Spatial Weights and Applications</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jiale SO </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 14, 2024</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">September 16, 2024</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="outcome-of-this-exercise" class="level1">
<h1>Outcome of this Exercise</h1>
<p>How to compute spatial weights using R. By the end to this hands-on exercise, you will be able to:</p>
<ul>
<li><p>import geospatial data using appropriate function(s) of <strong>sf</strong> package,</p></li>
<li><p>import csv file using appropriate function of <strong>readr</strong> package,</p></li>
<li><p>perform relational join using appropriate join function of <strong>dplyr</strong> package,</p></li>
<li><p>compute spatial weights using appropriate functions of <strong>spdep</strong> package, and</p></li>
<li><p>calculate spatially lagged variables using appropriate functions of <strong>spdep</strong> package.</p></li>
</ul>
</section>
<section id="setting-the-environment" class="level1">
<h1>1.0 Setting the Environment</h1>
<p>ensure that&nbsp;<strong>spdep</strong>,&nbsp;<strong>sf</strong>,&nbsp;<strong>tmap</strong>&nbsp;and&nbsp;<strong>tidyverse</strong>&nbsp;packages of R are currently installed&nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, spdep, tmap, tidyverse, knitr, tibble)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="importing-the-data" class="level1">
<h1>2.0 Importing the data</h1>
<p>Two data sets will be used in this hands-on exercise, they are:</p>
<ul>
<li><p>Hunan county boundary layer. This is a geospatial data set in ESRI shapefile format.</p></li>
<li><p>Hunan_2012.csv: This csv file contains selected Hunan’s local development indicators in 2012.</p></li>
</ul>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">ShapeFile</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">CSVFile with Left Join</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>hunan <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial"</span>, <span class="at">layer =</span> <span class="st">"Hunan"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `Hunan' from data source 
  `C:\Users\jiale\Desktop\IS415\IS415-GAA\Hands_On_Exercises\Hands_On_Exercise_5\data\geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 88 features and 7 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>hunan2012 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/aspatial/Hunan_2012.csv"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>hunan <span class="ot">&lt;-</span> <span class="fu">left_join</span>(hunan,hunan2012)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
<section id="visualising-regional-development-indicator" class="level1">
<h1><strong>3.0 Visualising Regional Development Indicator</strong></h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>basemap <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(hunan) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_text</span>(<span class="st">"NAME_3"</span>, <span class="at">size=</span><span class="fl">0.5</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>gdppc <span class="ot">&lt;-</span> <span class="fu">qtm</span>(hunan, <span class="st">"GDPPC"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(basemap, gdppc, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands_On_Exercise5_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="computing-contiguity-spatial-weights" class="level1">
<h1><strong>4.0 Computing Contiguity Spatial Weights</strong></h1>
<p>&nbsp;<a href="https://r-spatial.github.io/spdep/reference/poly2nb.html"><em>poly2nb()</em></a>&nbsp;of&nbsp;<strong>spdep</strong>&nbsp;package to compute contiguity weight matrices for the study area. This function builds a neighbours list based on regions with contiguous boundaries. Remember to use “pass” a queen argument that takes TRUE or FALSE as options, and it will return a list of first order neighbours using Queen Critiera</p>
<section id="computing-queen-contiguity-based-neighbours" class="level2">
<h2 class="anchored" data-anchor-id="computing-queen-contiguity-based-neighbours">4.1 <strong>Computing (QUEEN) contiguity based neighbours</strong></h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">Computing Queen Contiguity Weight Matrix</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<ul>
<li><p><strong><code>wm_q &lt;- poly2nb(hunan, queen=TRUE)</code></strong>:</p>
<ul>
<li><p><code>poly2nb</code> creates a neighborhood list based on polygon boundaries.</p></li>
<li><p><code>hunan</code> is the spatial polygon data (likely a <code>SpatialPolygonsDataFrame</code> or <code>sf</code> object).</p></li>
<li><p><code>queen=TRUE</code> specifies that the Queen contiguity rule should be used. This means that two polygons are considered neighbors if they share at least one point (either a boundary or a corner).</p></li>
<li><p><code>wm_q</code> stores the neighborhood structure as an object.</p></li>
</ul></li>
<li><p><strong><code>summary(wm_q)</code></strong>:</p>
<ul>
<li>This provides a summary of the neighborhood list, showing how many neighbors each polygon has and other summary statistics.</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>wm_q <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(hunan, <span class="at">queen=</span><span class="cn">TRUE</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wm_q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 88 
Number of nonzero links: 448 
Percentage nonzero weights: 5.785124 
Average number of links: 5.090909 
Link number distribution:

 1  2  3  4  5  6  7  8  9 11 
 2  2 12 16 24 14 11  4  2  1 
2 least connected regions:
30 65 with 1 link
1 most connected region:
85 with 11 links</code></pre>
</div>
</div>
<p>The summary report above shows that there are 88 area units in Hunan. The most connected area unit has 11 neighbours. There are two area units with only one heighbours.</p>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">Neighbours</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">Get Their Names</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-3" role="tab" aria-controls="tabset-3-3" aria-selected="false">Neighbour Names</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-4" role="tab" aria-controls="tabset-3-4" aria-selected="false">Retrieve the GDPPC of Neighbour countries With Names</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-5" role="tab" aria-controls="tabset-3-5" aria-selected="false">List Each Country’s Neighbour</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<p>For each polygon in our polygon object,&nbsp;<em>wm_q</em>&nbsp;lists all neighboring polygons. For example, to see the neighbors for the first polygon in the object, we use the following code chunk, to which we see they have 5 neighbours</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>wm_q[[<span class="dv">1</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  2  3  4 57 85</code></pre>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<p>We can retrive the county name of Polygon ID=1 by using the code chunk below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>hunan<span class="sc">$</span>County[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Anxiang"</code></pre>
</div>
</div>
<p>The output reveals that Polygon ID=1 is Anxiang county.</p>
</div>
<div id="tabset-3-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-3-tab">
<p>To reveal the county names of the five neighboring polygons, the code chunk will be used:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>hunan<span class="sc">$</span>NAME_3[<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">57</span>,<span class="dv">85</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Hanshou" "Jinshi"  "Li"      "Nan"     "Taoyuan"</code></pre>
</div>
</div>
</div>
<div id="tabset-3-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-4-tab">
<p>We can retrieve the GDPPC of these five countries by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>nb1 <span class="ot">&lt;-</span> wm_q[[<span class="dv">1</span>]]</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Retrieve the GDPPC values for the neighbors and the first polygon</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>gdp_values <span class="ot">&lt;-</span> <span class="fu">c</span>(hunan<span class="sc">$</span>GDPPC[<span class="dv">1</span>], hunan<span class="sc">$</span>GDPPC[nb1])</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Retrieve the county names for the first polygon and its neighbors</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>county_names <span class="ot">&lt;-</span> <span class="fu">c</span>(hunan<span class="sc">$</span>NAME_3[<span class="dv">1</span>], hunan<span class="sc">$</span>NAME_3[nb1])</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign the county names as names of the GDPPC values</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(gdp_values) <span class="ot">&lt;-</span> county_names</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the GDPPC values with county names</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>gdp_values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anxiang Hanshou  Jinshi      Li     Nan Taoyuan 
  23667   20981   34592   24473   21311   22879 </code></pre>
</div>
</div>
</div>
<div id="tabset-3-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-5-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize a list to store the data for all polygons</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>gdp_data <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">seq_along</span>(wm_q), <span class="cf">function</span>(i) {</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Get the neighbors of polygon i</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  neighbors <span class="ot">&lt;-</span> wm_q[[i]]</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Get the GDPPC values for the polygon and its neighbors</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  gdp_values <span class="ot">&lt;-</span> <span class="fu">c</span>(hunan<span class="sc">$</span>GDPPC[i], hunan<span class="sc">$</span>GDPPC[neighbors])</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Get the county names for the polygon and its neighbors</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  county_names <span class="ot">&lt;-</span> <span class="fu">c</span>(hunan<span class="sc">$</span>NAME_3[i], hunan<span class="sc">$</span>NAME_3[neighbors])</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create a tibble for each polygon with neighbors</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">Polygon =</span> county_names[<span class="dv">1</span>],  <span class="co"># Main polygon name</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">Neighbor =</span> county_names[<span class="sc">-</span><span class="dv">1</span>],  <span class="co"># Neighbor names</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">GDPPC =</span> gdp_values[<span class="sc">-</span><span class="dv">1</span>],  <span class="co"># Neighbor GDPPC values</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">Neighbour_GDPPC =</span> gdp_values[<span class="dv">1</span>]  <span class="co"># Main polygon GDPPC</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(data)</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine all rows into a single data frame</span></span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>gdp_df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(gdp_data)</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a><span class="co"># View the combined data in a cleaner format</span></span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>gdp_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 448 × 4
   Polygon Neighbor  GDPPC Neighbour_GDPPC
   &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt;           &lt;dbl&gt;
 1 Anxiang Hanshou   20981           23667
 2 Anxiang Jinshi    34592           23667
 3 Anxiang Li        24473           23667
 4 Anxiang Nan       21311           23667
 5 Anxiang Taoyuan   22879           23667
 6 Hanshou Anxiang   23667           20981
 7 Hanshou Nan       21311           20981
 8 Hanshou Yuanjiang 26258           20981
 9 Hanshou Taojiang  19509           20981
10 Hanshou Taoyuan   22879           20981
# ℹ 438 more rows</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="creating-rook-contiguity-based-neighbours" class="level2">
<h2 class="anchored" data-anchor-id="creating-rook-contiguity-based-neighbours">4.2 <strong>Creating (ROOK) contiguity based neighbours</strong></h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">Computing Root Contiguity Weight Matrix</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<p>Instead of queen true, we use False here</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>wm_r  <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(hunan, <span class="at">queen=</span> <span class="cn">FALSE</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wm_q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 88 
Number of nonzero links: 448 
Percentage nonzero weights: 5.785124 
Average number of links: 5.090909 
Link number distribution:

 1  2  3  4  5  6  7  8  9 11 
 2  2 12 16 24 14 11  4  2  1 
2 least connected regions:
30 65 with 1 link
1 most connected region:
85 with 11 links</code></pre>
</div>
</div>
<p>The summary report above shows that there are 88 area units in Hunan using the rook. The most connected area unit has 10 neighbours. There are two area units with only one heighbours.</p>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true">Neighbours</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false">Get Their Names</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-3" role="tab" aria-controls="tabset-5-3" aria-selected="false">Neighbour Names</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-4" role="tab" aria-controls="tabset-5-4" aria-selected="false">Retrieve the GDPPC of Neighbour countries With Names</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-5" role="tab" aria-controls="tabset-5-5" aria-selected="false">List Each Country’s Neighbour</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<p>For each polygon in our polygon object,&nbsp;<em>wm_q</em>&nbsp;lists all neighboring polygons. For example, to see the neighbors for the first polygon in the object, we use the following code chunk, to which we see they have 4 neighbours</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>wm_r[[<span class="dv">1</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  3  4 57 85</code></pre>
</div>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<p>We can retrive the county name of Polygon ID=1 by using the code chunk below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>hunan<span class="sc">$</span>County[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Anxiang"</code></pre>
</div>
</div>
<p>The output reveals that Polygon ID=1 is Anxiang county.</p>
</div>
<div id="tabset-5-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-3-tab">
<p>To reveal the county names of the five neighboring polygons, the code chunk will be used:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>hunan<span class="sc">$</span>NAME_3[<span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">57</span>,<span class="dv">85</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Jinshi"  "Li"      "Nan"     "Taoyuan"</code></pre>
</div>
</div>
</div>
<div id="tabset-5-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-4-tab">
<p>We can retrieve the GDPPC of these five countries by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>nb1 <span class="ot">&lt;-</span> wm_r[[<span class="dv">1</span>]]</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Retrieve the GDPPC values for the neighbors and the first polygon</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>gdp_values <span class="ot">&lt;-</span> <span class="fu">c</span>(hunan<span class="sc">$</span>GDPPC[<span class="dv">1</span>], hunan<span class="sc">$</span>GDPPC[nb1])</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Retrieve the county names for the first polygon and its neighbors</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>county_names <span class="ot">&lt;-</span> <span class="fu">c</span>(hunan<span class="sc">$</span>NAME_3[<span class="dv">1</span>], hunan<span class="sc">$</span>NAME_3[nb1])</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign the county names as names of the GDPPC values</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(gdp_values) <span class="ot">&lt;-</span> county_names</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the GDPPC values with county names</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>gdp_values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anxiang  Jinshi      Li     Nan Taoyuan 
  23667   34592   24473   21311   22879 </code></pre>
</div>
</div>
</div>
<div id="tabset-5-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-5-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize a list to store the data for all polygons</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>gdp_data <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">seq_along</span>(wm_q), <span class="cf">function</span>(i) {</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Get the neighbors of polygon i</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  neighbors <span class="ot">&lt;-</span> wm_r[[i]]</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Get the GDPPC values for the polygon and its neighbors</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  gdp_values <span class="ot">&lt;-</span> <span class="fu">c</span>(hunan<span class="sc">$</span>GDPPC[i], hunan<span class="sc">$</span>GDPPC[neighbors])</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Get the county names for the polygon and its neighbors</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  county_names <span class="ot">&lt;-</span> <span class="fu">c</span>(hunan<span class="sc">$</span>NAME_3[i], hunan<span class="sc">$</span>NAME_3[neighbors])</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create a tibble for each polygon with neighbors</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">Polygon =</span> county_names[<span class="dv">1</span>],  <span class="co"># Main polygon name</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">Neighbor =</span> county_names[<span class="sc">-</span><span class="dv">1</span>],  <span class="co"># Neighbor names</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">GDPPC =</span> gdp_values[<span class="sc">-</span><span class="dv">1</span>],  <span class="co"># Neighbor GDPPC values</span></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">Neighbour_GDPPC =</span> gdp_values[<span class="dv">1</span>]  <span class="co"># Main polygon GDPPC</span></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(data)</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine all rows into a single data frame</span></span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a>gdp_df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(gdp_data)</span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a><span class="co"># View the combined data in a cleaner format</span></span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a>gdp_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 440 × 4
   Polygon Neighbor  GDPPC Neighbour_GDPPC
   &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt;           &lt;dbl&gt;
 1 Anxiang Jinshi    34592           23667
 2 Anxiang Li        24473           23667
 3 Anxiang Nan       21311           23667
 4 Anxiang Taoyuan   22879           23667
 5 Hanshou Nan       21311           20981
 6 Hanshou Yuanjiang 26258           20981
 7 Hanshou Taojiang  19509           20981
 8 Hanshou Taoyuan   22879           20981
 9 Jinshi  Anxiang   23667           34592
10 Jinshi  Li        24473           34592
# ℹ 430 more rows</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="visualizing-contiguity-weights" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-contiguity-weights">4.3 Visualizing Contiguity Weights</h2>
<p>To create a connectivity graph for polygons, we first need to obtain points for each polygon, which can be done using their centroids. The centroids will serve as the points for the graph.</p>
<p>The process involves calculating the centroids using the <code>sf</code> package. Instead of directly using <code>st_centroid</code> on the spatial data object, we need to extract the centroid coordinates into a separate data frame. This is done by applying the <code>st_centroid</code> function to the geometry column of the spatial data using a mapping function (<code>map_dbl</code> from the <code>purrr</code> package).</p>
<p>By mapping <code>st_centroid</code> over the geometry column, we can extract the longitude (the first value in each centroid) using double bracket notation <code>[[1]]</code>. This prepares the longitude values for further use in creating the connectivity graph.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>longitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(hunan<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">1</span>]]) <span class="co">#This allows us to get only the longitude, which is the first value in each centroid.</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>latitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(hunan<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">2</span>]]) <span class="co">#We do the same for latitude with one key difference. We access the second value per each centroid with [[2]].</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">cbind</span>(longitude, latitude) <span class="co"># Now that we have latitude and longitude, we use cbind to put longitude and latitude into the same object.</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coords) <span class="co">#We check the first few observations to see if things are formatted correctly.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     longitude latitude
[1,]  112.1531 29.44362
[2,]  112.0372 28.86489
[3,]  111.8917 29.47107
[4,]  111.7031 29.74499
[5,]  111.6138 29.49258
[6,]  111.0341 29.79863</code></pre>
</div>
</div>
<section id="plotting-contiguity-based-neighbours-map" class="level3">
<h3 class="anchored" data-anchor-id="plotting-contiguity-based-neighbours-map">4.3.1 Plotting Contiguity based Neighbours Map</h3>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true">Queen’s</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false">King’s</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-3" role="tab" aria-controls="tabset-6-3" aria-selected="false">Side By Side Comparison</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hunan<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wm_q, coords, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col=</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands_On_Exercise5_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hunan<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wm_r, coords, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col=</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands_On_Exercise5_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-6-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-3-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hunan<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>, <span class="at">main=</span><span class="st">"Queen Contiguity"</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wm_q, coords, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col=</span> <span class="st">"red"</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hunan<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>, <span class="at">main=</span><span class="st">"Rook Contiguity"</span>)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wm_r, coords, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands_On_Exercise5_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="computing-distance-based-neighbors" class="level1">
<h1>5.0 Computing Distance Based Neighbors</h1>
<p>Using the <code>dnearneigh()</code> function from the <code>spdep</code> package. The function identifies neighbors within a specified distance range (distance band) using Euclidean distances.</p>
<section id="key-steps" class="level3">
<h3 class="anchored" data-anchor-id="key-steps">Key Steps:</h3>
<ol type="1">
<li><p><strong>Determining the Cut-off Distance</strong>:</p>
<ul>
<li>The goal is to find an upper limit for the distance band by following a few steps using <code>knearneigh()</code>, <code>knn2nb()</code>, and <code>nbdists()</code>.</li>
</ul></li>
<li><p><strong>Procedure</strong>:</p>
<ul>
<li><p><strong>Step 1</strong>: Use <code>knearneigh()</code> to find the <code>k</code> nearest neighbors for each point. This returns an object representing the neighborhood relationships between regions.</p></li>
<li><p><strong>Step 2</strong>: Convert the nearest neighbor object into a neighbors list using <code>knn2nb()</code>. This converts the relationships into integer vectors containing the IDs of neighboring regions.</p></li>
<li><p><strong>Step 3</strong>: Calculate the distances between neighboring points using <code>nbdists()</code>, which returns the distances in the same units as the coordinates or in kilometers if the coordinates are unprojected.</p></li>
<li><p><strong>Step 4</strong>: Use <code>unlist()</code> to flatten the list structure of the distances returned by <code>nbdists()</code>.</p></li>
</ul></li>
</ol>
</section>
<section id="determine-cut-off-distance" class="level2">
<h2 class="anchored" data-anchor-id="determine-cut-off-distance">5.1 Determine Cut-Off Distance</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the coordinates of the regions</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co">#coords &lt;- coordinates(hunan)</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the k-nearest neighbors</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>k1 <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords))</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the distances between the neighbors</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>k1dists <span class="ot">&lt;-</span> <span class="fu">unlist</span>(<span class="fu">nbdists</span>(k1, coords, <span class="at">longlat =</span> <span class="cn">TRUE</span>))</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Display a summary of the distances</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(k1dists)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  24.79   32.57   38.01   39.07   44.52   61.79 </code></pre>
</div>
</div>
<p>The summary report shows that the largest first nearest neighbour distance is 61.79 km, so using this as the upper threshold gives certainty that all units will have at least one neighbour.</p>
</section>
<section id="computing-fixed-and-adaptive-distance-weight-matrix" class="level2">
<h2 class="anchored" data-anchor-id="computing-fixed-and-adaptive-distance-weight-matrix">5.2 Computing Fixed and Adaptive Distance Weight Matrix</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>When to use fixed or adaptive?</strong></p>
<ul>
<li><p><strong>Fixed Distance Weighting</strong>: Use when spatial points are distributed evenly and when you want a constant radius of influence for all regions.</p></li>
<li><p><strong>Adaptive Distance Weighting</strong>: Use when spatial points are unevenly distributed and when you want each region to have a comparable number of neighbors, regardless of their physical distance.</p></li>
</ul>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true">Fixed Distance</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false">Adaptive Distance</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<p>Compute the distance weight matrix by using&nbsp;<em>dnearneigh()</em>&nbsp;as shown in the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>wm_d62 <span class="ot">&lt;-</span> <span class="fu">dnearneigh</span>(coords, <span class="dv">0</span>, <span class="dv">62</span>, <span class="at">longlat =</span> <span class="cn">TRUE</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>wm_d62</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 88 
Number of nonzero links: 324 
Percentage nonzero weights: 4.183884 
Average number of links: 3.681818 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Quiz:</strong> What is the meaning of “Average number of links: 3.681818” shown above?</p>
<p><strong>“Average number of links: 3.681818”</strong> refers to the <strong>average number of neighboring regions</strong> each region in the dataset has, based on the distance threshold defined earlier 62km.</p>
<p><strong>“Average number of links: 3.681818”</strong> means that, on average, each region has around 3.68 neighbors within a 62-kilometer radius.</p>
</div>
</div>
<p><strong>Visualizing the weight matrix</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>neighbor_counts <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">County =</span> hunan<span class="sc">$</span>County,</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Neighbors =</span> <span class="fu">card</span>(wm_d62)  <span class="co"># card() gives the number of neighbors for each region</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="co"># View the data frame</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(neighbor_counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          County Neighbors
1        Anxiang         5
2        Hanshou         4
3         Jinshi         4
4             Li         3
5          Linli         4
6         Shimen         1
7        Liuyang         2
8      Ningxiang         4
9      Wangcheng         4
10         Anren         4
11       Guidong         3
12         Jiahe         5
13         Linwu         4
14       Rucheng         2
15       Yizhang         1
16      Yongxing         4
17        Zixing         3
18     Changning         3
19      Hengdong         5
20       Hengnan         5
21      Hengshan         6
22       Leiyang         4
23        Qidong         3
24        Chenxi         4
25     Zhongfang         4
26       Huitong         4
27      Jingzhou         2
28        Mayang         6
29       Tongdao         2
30      Xinhuang         1
31          Xupu         2
32      Yuanling         1
33      Zhijiang         5
34 Lengshuijiang         3
35    Shuangfeng         6
36        Xinhua         5
37       Chengbu         2
38        Dongan         3
39       Dongkou         4
40       Longhui         3
41      Shaodong         5
42       Suining         5
43        Wugang         3
44       Xinning         2
45       Xinshao         6
46      Shaoshan         5
47    Xiangxiang         5
48       Baojing         5
49     Fenghuang         4
50       Guzhang         6
51       Huayuan         4
52        Jishou         6
53      Longshan         2
54          Luxi         5
55      Yongshun         4
56         Anhua         1
57           Nan         5
58     Yuanjiang         5
59      Jianghua         3
60       Lanshan         4
61      Ningyuan         5
62     Shuangpai         4
63       Xintian         5
64       Huarong         4
65      Linxiang         1
66         Miluo         5
67     Pingjiang         2
68      Xiangyin         4
69          Cili         2
70       Chaling         3
71        Liling         2
72       Yanling         3
73           You         4
74       Zhuzhou         5
75       Sangzhi         2
76       Yueyang         3
77        Qiyang         3
78      Taojiang         2
79      Shaoyang         4
80      Lianyuan         5
81     Hongjiang         5
82      Hengyang         6
83       Guiyang         4
84      Changsha         4
85       Taoyuan         2
86      Xiangtan         4
87           Dao         4
88     Jiangyong         2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Or use View() in RStudio for an interactive table view</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Plotting It</strong></p>
<ul>
<li><p><strong>First Plot</strong>: The <strong>base map</strong> of the regions (Hunan) is drawn using their geographic boundaries.</p></li>
<li><p><strong>Second Plot</strong>: The <strong>distance-based neighbor links</strong> are added, connecting regions that are within 62 km of each other.</p></li>
<li><p><strong>Third Plot</strong>: The <strong>k-nearest neighbor links</strong> are added as <strong>red arrows</strong>, showing the regions’ closest neighbors.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hunan<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wm_d62, coords, <span class="at">add=</span><span class="cn">TRUE</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(k1, coords, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">length=</span><span class="fl">0.08</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands_On_Exercise5_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Comparing it against 1st nearest and distance link.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hunan<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>, <span class="at">main=</span><span class="st">"1st nearest neighbours"</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(k1, coords, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">length=</span><span class="fl">0.08</span>)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hunan<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>, <span class="at">main=</span><span class="st">"Distance link"</span>)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wm_d62, coords, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands_On_Exercise5_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<p>It is possible to control the numbers of neighbours directly using k-nearest neighbours, either accepting asymmetric neighbours or imposing symmetry as shown in the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>knn6 <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords, <span class="at">k=</span><span class="dv">6</span>))</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>knn6</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 88 
Number of nonzero links: 528 
Percentage nonzero weights: 6.818182 
Average number of links: 6 
Non-symmetric neighbours list</code></pre>
</div>
</div>
<p>Similarly, we can display the content of the matrix by using <em>str()</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(knn6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 88
 $ : int [1:6] 2 3 4 5 57 64
 $ : int [1:6] 1 3 57 58 78 85
 $ : int [1:6] 1 2 4 5 57 85
 $ : int [1:6] 1 3 5 6 69 85
 $ : int [1:6] 1 3 4 6 69 85
 $ : int [1:6] 3 4 5 69 75 85
 $ : int [1:6] 9 66 67 71 74 84
 $ : int [1:6] 9 46 47 78 80 86
 $ : int [1:6] 8 46 66 68 84 86
 $ : int [1:6] 16 19 22 70 72 73
 $ : int [1:6] 10 14 16 17 70 72
 $ : int [1:6] 13 15 60 61 63 83
 $ : int [1:6] 12 15 60 61 63 83
 $ : int [1:6] 11 15 16 17 72 83
 $ : int [1:6] 12 13 14 17 60 83
 $ : int [1:6] 10 11 17 22 72 83
 $ : int [1:6] 10 11 14 16 72 83
 $ : int [1:6] 20 22 23 63 77 83
 $ : int [1:6] 10 20 21 73 74 82
 $ : int [1:6] 18 19 21 22 23 82
 $ : int [1:6] 19 20 35 74 82 86
 $ : int [1:6] 10 16 18 19 20 83
 $ : int [1:6] 18 20 41 77 79 82
 $ : int [1:6] 25 28 31 52 54 81
 $ : int [1:6] 24 28 31 33 54 81
 $ : int [1:6] 25 27 29 33 42 81
 $ : int [1:6] 26 29 30 37 42 81
 $ : int [1:6] 24 25 33 49 52 54
 $ : int [1:6] 26 27 37 42 43 81
 $ : int [1:6] 26 27 28 33 49 81
 $ : int [1:6] 24 25 36 39 40 54
 $ : int [1:6] 24 31 50 54 55 56
 $ : int [1:6] 25 26 28 30 49 81
 $ : int [1:6] 36 40 41 45 56 80
 $ : int [1:6] 21 41 46 47 80 82
 $ : int [1:6] 31 34 40 45 56 80
 $ : int [1:6] 26 27 29 42 43 44
 $ : int [1:6] 23 43 44 62 77 79
 $ : int [1:6] 25 40 42 43 44 81
 $ : int [1:6] 31 36 39 43 45 79
 $ : int [1:6] 23 35 45 79 80 82
 $ : int [1:6] 26 27 37 39 43 81
 $ : int [1:6] 37 39 40 42 44 79
 $ : int [1:6] 37 38 39 42 43 79
 $ : int [1:6] 34 36 40 41 79 80
 $ : int [1:6] 8 9 35 47 78 86
 $ : int [1:6] 8 21 35 46 80 86
 $ : int [1:6] 49 50 51 52 53 55
 $ : int [1:6] 28 33 48 51 52 54
 $ : int [1:6] 32 48 51 52 54 55
 $ : int [1:6] 28 48 49 50 52 54
 $ : int [1:6] 28 48 49 50 51 54
 $ : int [1:6] 48 50 51 52 55 75
 $ : int [1:6] 24 28 49 50 51 52
 $ : int [1:6] 32 48 50 52 53 75
 $ : int [1:6] 32 34 36 78 80 85
 $ : int [1:6] 1 2 3 58 64 68
 $ : int [1:6] 2 57 64 66 68 78
 $ : int [1:6] 12 13 60 61 87 88
 $ : int [1:6] 12 13 59 61 63 87
 $ : int [1:6] 12 13 60 62 63 87
 $ : int [1:6] 12 38 61 63 77 87
 $ : int [1:6] 12 18 60 61 62 83
 $ : int [1:6] 1 3 57 58 68 76
 $ : int [1:6] 58 64 66 67 68 76
 $ : int [1:6] 9 58 67 68 76 84
 $ : int [1:6] 7 65 66 68 76 84
 $ : int [1:6] 9 57 58 66 78 84
 $ : int [1:6] 4 5 6 32 75 85
 $ : int [1:6] 10 16 19 22 72 73
 $ : int [1:6] 7 19 73 74 84 86
 $ : int [1:6] 10 11 14 16 17 70
 $ : int [1:6] 10 19 21 70 71 74
 $ : int [1:6] 19 21 71 73 84 86
 $ : int [1:6] 6 32 50 53 55 69
 $ : int [1:6] 58 64 65 66 67 68
 $ : int [1:6] 18 23 38 61 62 63
 $ : int [1:6] 2 8 9 46 58 68
 $ : int [1:6] 38 40 41 43 44 45
 $ : int [1:6] 34 35 36 41 45 47
 $ : int [1:6] 25 26 28 33 39 42
 $ : int [1:6] 19 20 21 23 35 41
 $ : int [1:6] 12 13 15 16 22 63
 $ : int [1:6] 7 9 66 68 71 74
 $ : int [1:6] 2 3 4 5 56 69
 $ : int [1:6] 8 9 21 46 47 74
 $ : int [1:6] 59 60 61 62 63 88
 $ : int [1:6] 59 60 61 62 63 87
 - attr(*, "region.id")= chr [1:88] "1" "2" "3" "4" ...
 - attr(*, "call")= language knearneigh(x = coords, k = 6)
 - attr(*, "sym")= logi FALSE
 - attr(*, "type")= chr "knn"
 - attr(*, "knn-k")= num 6
 - attr(*, "class")= chr "nb"</code></pre>
</div>
</div>
<p><strong>Plotting it and against 1st nearest and distance link</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hunan<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>, <span class="at">main=</span><span class="st">"1st nearest neighbours"</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(k1, coords, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">length=</span><span class="fl">0.08</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hunan<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>, <span class="at">main=</span><span class="st">"Distance link"</span>)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(knn6, coords, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands_On_Exercise5_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="weight-based-on-in-versed-distance-method." class="level1">
<h1>6.0 Weight Based on In-versed Distance Method.</h1>
<p>The <strong>inverse distance weighting (IDW)</strong> method is a technique used in spatial analysis to assign weights to neighboring regions or points based on their distance. The core idea is that <strong>closer neighbors exert a stronger influence</strong>, and the weight of a neighbor decreases as its distance increases. In the inverse distance method, weights are inversely proportional to the distance between points, meaning that the closer two points are, the higher the weight assigned to their relationship.</p>
<p>First, we will compute the distances between areas by using&nbsp;<a href="https://r-spatial.github.io/spdep/reference/nbdists.html"><em>nbdists()</em></a>&nbsp;of&nbsp;<strong>spdep</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>dist <span class="ot">&lt;-</span> <span class="fu">nbdists</span>(wm_q, coords, <span class="at">longlat =</span> <span class="cn">TRUE</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>ids <span class="ot">&lt;-</span> <span class="fu">lapply</span>(dist, <span class="cf">function</span>(x) <span class="dv">1</span><span class="sc">/</span>(x))</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>ids</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 0.01535405 0.03916350 0.01820896 0.02807922 0.01145113

[[2]]
[1] 0.01535405 0.01764308 0.01925924 0.02323898 0.01719350

[[3]]
[1] 0.03916350 0.02822040 0.03695795 0.01395765

[[4]]
[1] 0.01820896 0.02822040 0.03414741 0.01539065

[[5]]
[1] 0.03695795 0.03414741 0.01524598 0.01618354

[[6]]
[1] 0.015390649 0.015245977 0.021748129 0.011883901 0.009810297

[[7]]
[1] 0.01708612 0.01473997 0.01150924 0.01872915

[[8]]
[1] 0.02022144 0.03453056 0.02529256 0.01036340 0.02284457 0.01500600 0.01515314

[[9]]
[1] 0.02022144 0.01574888 0.02109502 0.01508028 0.02902705 0.01502980

[[10]]
[1] 0.02281552 0.01387777 0.01538326 0.01346650 0.02100510 0.02631658 0.01874863
[8] 0.01500046

[[11]]
[1] 0.01882869 0.02243492 0.02247473

[[12]]
[1] 0.02779227 0.02419652 0.02333385 0.02986130 0.02335429

[[13]]
[1] 0.02779227 0.02650020 0.02670323 0.01714243

[[14]]
[1] 0.01882869 0.01233868 0.02098555

[[15]]
[1] 0.02650020 0.01233868 0.01096284 0.01562226

[[16]]
[1] 0.02281552 0.02466962 0.02765018 0.01476814 0.01671430

[[17]]
[1] 0.01387777 0.02243492 0.02098555 0.01096284 0.02466962 0.01593341 0.01437996

[[18]]
[1] 0.02039779 0.02032767 0.01481665 0.01473691 0.01459380

[[19]]
[1] 0.01538326 0.01926323 0.02668415 0.02140253 0.01613589 0.01412874

[[20]]
[1] 0.01346650 0.02039779 0.01926323 0.01723025 0.02153130 0.01469240 0.02327034

[[21]]
[1] 0.02668415 0.01723025 0.01766299 0.02644986 0.02163800

[[22]]
[1] 0.02100510 0.02765018 0.02032767 0.02153130 0.01489296

[[23]]
[1] 0.01481665 0.01469240 0.01401432 0.02246233 0.01880425 0.01530458 0.01849605

[[24]]
[1] 0.02354598 0.01837201 0.02607264 0.01220154 0.02514180

[[25]]
[1] 0.02354598 0.02188032 0.01577283 0.01949232 0.02947957

[[26]]
[1] 0.02155798 0.01745522 0.02212108 0.02220532

[[27]]
[1] 0.02155798 0.02490625 0.01562326

[[28]]
[1] 0.01837201 0.02188032 0.02229549 0.03076171 0.02039506

[[29]]
[1] 0.02490625 0.01686587 0.01395022

[[30]]
[1] 0.02090587

[[31]]
[1] 0.02607264 0.01577283 0.01219005 0.01724850 0.01229012 0.01609781 0.01139438
[8] 0.01150130

[[32]]
[1] 0.01220154 0.01219005 0.01712515 0.01340413 0.01280928 0.01198216 0.01053374
[8] 0.01065655

[[33]]
[1] 0.01949232 0.01745522 0.02229549 0.02090587 0.01979045

[[34]]
[1] 0.03113041 0.03589551 0.02882915

[[35]]
[1] 0.01766299 0.02185795 0.02616766 0.02111721 0.02108253 0.01509020

[[36]]
[1] 0.01724850 0.03113041 0.01571707 0.01860991 0.02073549 0.01680129

[[37]]
[1] 0.01686587 0.02234793 0.01510990 0.01550676

[[38]]
[1] 0.01401432 0.02407426 0.02276151 0.01719415

[[39]]
[1] 0.01229012 0.02172543 0.01711924 0.02629732 0.01896385

[[40]]
[1] 0.01609781 0.01571707 0.02172543 0.01506473 0.01987922 0.01894207

[[41]]
[1] 0.02246233 0.02185795 0.02205991 0.01912542 0.01601083 0.01742892

[[42]]
[1] 0.02212108 0.01562326 0.01395022 0.02234793 0.01711924 0.01836831 0.01683518

[[43]]
[1] 0.01510990 0.02629732 0.01506473 0.01836831 0.03112027 0.01530782

[[44]]
[1] 0.01550676 0.02407426 0.03112027 0.01486508

[[45]]
[1] 0.03589551 0.01860991 0.01987922 0.02205991 0.02107101 0.01982700

[[46]]
[1] 0.03453056 0.04033752 0.02689769

[[47]]
[1] 0.02529256 0.02616766 0.04033752 0.01949145 0.02181458

[[48]]
[1] 0.02313819 0.03370576 0.02289485 0.01630057 0.01818085

[[49]]
[1] 0.03076171 0.02138091 0.02394529 0.01990000

[[50]]
[1] 0.01712515 0.02313819 0.02551427 0.02051530 0.02187179

[[51]]
[1] 0.03370576 0.02138091 0.02873854

[[52]]
[1] 0.02289485 0.02394529 0.02551427 0.02873854 0.03516672

[[53]]
[1] 0.01630057 0.01979945 0.01253977

[[54]]
[1] 0.02514180 0.02039506 0.01340413 0.01990000 0.02051530 0.03516672

[[55]]
[1] 0.01280928 0.01818085 0.02187179 0.01979945 0.01882298

[[56]]
[1] 0.01036340 0.01139438 0.01198216 0.02073549 0.01214479 0.01362855 0.01341697

[[57]]
[1] 0.028079221 0.017643082 0.031423501 0.029114131 0.013520292 0.009903702

[[58]]
[1] 0.01925924 0.03142350 0.02722997 0.01434859 0.01567192

[[59]]
[1] 0.01696711 0.01265572 0.01667105 0.01785036

[[60]]
[1] 0.02419652 0.02670323 0.01696711 0.02343040

[[61]]
[1] 0.02333385 0.01265572 0.02343040 0.02514093 0.02790764 0.01219751 0.02362452

[[62]]
[1] 0.02514093 0.02002219 0.02110260

[[63]]
[1] 0.02986130 0.02790764 0.01407043 0.01805987

[[64]]
[1] 0.02911413 0.01689892

[[65]]
[1] 0.02471705

[[66]]
[1] 0.01574888 0.01726461 0.03068853 0.01954805 0.01810569

[[67]]
[1] 0.01708612 0.01726461 0.01349843 0.01361172

[[68]]
[1] 0.02109502 0.02722997 0.03068853 0.01406357 0.01546511

[[69]]
[1] 0.02174813 0.01645838 0.01419926

[[70]]
[1] 0.02631658 0.01963168 0.02278487

[[71]]
[1] 0.01473997 0.01838483 0.03197403

[[72]]
[1] 0.01874863 0.02247473 0.01476814 0.01593341 0.01963168

[[73]]
[1] 0.01500046 0.02140253 0.02278487 0.01838483 0.01652709

[[74]]
[1] 0.01150924 0.01613589 0.03197403 0.01652709 0.01342099 0.02864567

[[75]]
[1] 0.011883901 0.010533736 0.012539774 0.018822977 0.016458383 0.008217581

[[76]]
[1] 0.01352029 0.01434859 0.01689892 0.02471705 0.01954805 0.01349843 0.01406357

[[77]]
[1] 0.014736909 0.018804247 0.022761507 0.012197506 0.020022195 0.014070428
[7] 0.008440896

[[78]]
[1] 0.02323898 0.02284457 0.01508028 0.01214479 0.01567192 0.01546511 0.01140779

[[79]]
[1] 0.01530458 0.01719415 0.01894207 0.01912542 0.01530782 0.01486508 0.02107101

[[80]]
[1] 0.01500600 0.02882915 0.02111721 0.01680129 0.01601083 0.01982700 0.01949145
[8] 0.01362855

[[81]]
[1] 0.02947957 0.02220532 0.01150130 0.01979045 0.01896385 0.01683518

[[82]]
[1] 0.02327034 0.02644986 0.01849605 0.02108253 0.01742892

[[83]]
[1] 0.023354289 0.017142433 0.015622258 0.016714303 0.014379961 0.014593799
[7] 0.014892965 0.018059871 0.008440896

[[84]]
[1] 0.01872915 0.02902705 0.01810569 0.01361172 0.01342099 0.01297994

[[85]]
 [1] 0.011451133 0.017193502 0.013957649 0.016183544 0.009810297 0.010656545
 [7] 0.013416965 0.009903702 0.014199260 0.008217581 0.011407794

[[86]]
[1] 0.01515314 0.01502980 0.01412874 0.02163800 0.01509020 0.02689769 0.02181458
[8] 0.02864567 0.01297994

[[87]]
[1] 0.01667105 0.02362452 0.02110260 0.02058034

[[88]]
[1] 0.01785036 0.02058034</code></pre>
</div>
</div>
<ol type="1">
<li><p><strong><code>dist</code></strong>: Calculates the distances between each region and its neighbors.</p></li>
<li><p><strong><code>lapply()</code> with <code>1/(x)</code></strong>: Applies the inverse distance formula to those distances, assigning higher weights to closer neighbors.</p></li>
<li><p><strong><code>ids</code></strong>: Stores the <strong>inverse distance weights</strong> for each region’s neighbors, which can be used in spatial modeling or analysis to emphasize the influence of closer regions over more distant ones.</p></li>
</ol>
<p>The inverse distance method here helps quantify the influence of neighbors, where closer neighbors exert a stronger influence compared to those farther away.</p>
</section>
<section id="row-standardized-weight-matrix" class="level1">
<h1>7.0 Row-standardized Weight Matrix</h1>
<p>Assigning <strong>spatial weights</strong> to neighboring polygons using the <strong>“W” style</strong>, which stands for <strong>row-standardized weights</strong>.</p>
<section id="key-concepts" class="level3">
<h3 class="anchored" data-anchor-id="key-concepts">Key Concepts:</h3>
<ol type="1">
<li><p><strong>Row-Standardized Weights (style=“W”)</strong>:</p>
<ul>
<li><p>In this method, each neighboring polygon is assigned an <strong>equal weight</strong>.</p></li>
<li><p>The weight assigned to each neighbor is the inverse of the total number of neighbors for the polygon.</p></li>
<li><p>For example, if a polygon has 5 neighbors, the weight assigned to each of its neighbors is 1551​.</p></li>
</ul></li>
<li><p><strong>Summing Weighted Values</strong>:</p>
<ul>
<li><p>This method sums up the weighted values from each neighboring polygon. The row-standardized weights ensure that the weights for a polygon’s neighbors sum up to 1.</p></li>
<li><p><strong>Edge effect</strong>: Polygons at the edge of the study area may have fewer neighbors, potentially leading to biased estimates of spatial autocorrelation, as their weights are distributed over fewer polygons.</p></li>
</ul></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>rswm_q <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(wm_q, <span class="at">style=</span><span class="st">"W"</span>, <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>rswm_q</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 88 
Number of nonzero links: 448 
Percentage nonzero weights: 5.785124 
Average number of links: 5.090909 

Weights style: W 
Weights constants summary:
   n   nn S0       S1       S2
W 88 7744 88 37.86334 365.9147</code></pre>
</div>
</div>
<ul>
<li><p><strong><code>nb2listw()</code></strong>: Converts the neighbor list <code>wm_q</code> into a row-standardized spatial weights matrix.</p></li>
<li><p><strong><code>zero.policy = TRUE</code></strong>: Allows regions with no neighbors to be included, assigning them a weight of zero. This prevents errors for polygons without neighbors, though it should be used with caution to avoid inadvertently missing important spatial relationships.</p></li>
</ul>
<p>To see the weight of the first polygon’s eight neighbors type</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>rswm_q<span class="sc">$</span>weights[<span class="dv">10</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125</code></pre>
</div>
</div>
<p>In this case, if the 10th polygon has 8 neighbors, each neighbor will receive a weight of 18=0.125 = 0.12581​=0.125. This means that when computing a spatially lagged variable (such as average neighboring income), each neighbor’s income will be multiplied by 0.125 before summing.</p>
<p>We can also create a <strong>row-standardized distance weight matrix</strong> based on inverse distances. This adjusts the weights by incorporating the inverse distance method while ensuring that the weights for each polygon still sum to 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>rswm_ids <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(wm_q, <span class="at">glist=</span>ids, <span class="at">style=</span><span class="st">"B"</span>, <span class="at">zero.policy=</span><span class="cn">TRUE</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>rswm_ids</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 88 
Number of nonzero links: 448 
Percentage nonzero weights: 5.785124 
Average number of links: 5.090909 

Weights style: B 
Weights constants summary:
   n   nn       S0        S1     S2
B 88 7744 8.786867 0.3776535 3.8137</code></pre>
</div>
</div>
<ul>
<li><p><strong><code>glist=ids</code></strong>: Incorporates the inverse distance weights (<code>ids</code>) calculated earlier into the weight matrix.</p></li>
<li><p><strong><code>style="B"</code></strong>: This is a <strong>binary weighting</strong> scheme, where the weights are not normalized to sum to 1.</p></li>
</ul>
<p>To inspect the weights for the first polygon:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>rswm_ids<span class="sc">$</span>weights[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 0.01535405 0.03916350 0.01820896 0.02807922 0.01145113</code></pre>
</div>
</div>
<p>This shows the inverse distance weights for the first polygon’s neighbors. To summarize the distribution of all weights across the dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">unlist</span>(rswm_ids<span class="sc">$</span>weights))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
0.008218 0.015088 0.018739 0.019614 0.022823 0.040338 </code></pre>
</div>
</div>
</section>
</section>
<section id="application-of-spatial-weight-matrix" class="level1">
<h1>8.0 <strong>Application of Spatial Weight Matrix</strong></h1>
<section id="spatial-lag-with-row-standardized-weights" class="level2">
<h2 class="anchored" data-anchor-id="spatial-lag-with-row-standardized-weights">8.1 spatial lag with row-standardized weights</h2>
<p>compute the average neighbor GDPPC value for each polygon. These values are often referred to as&nbsp;<strong>spatially lagged values</strong>.</p>
<p><strong><code>lag.listw(rswm_q, hunan$GDPPC)</code></strong>:</p>
<ul>
<li><p>This calculates the <strong>spatial lag</strong> of GDP per capita (GDPPC) for each region using the <strong>row-standardized weights</strong> (<code>rswm_q</code>).</p></li>
<li><p>For each region, the function computes the weighted average of the GDPPC values of its neighboring regions.</p></li>
<li><p>Since we are using row-standardized weights, the influence of each neighboring region is scaled based on the number of neighbors. If a region has 4 neighbors, each neighbor’s influence will be 1441​.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>GDPPC.lag <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(rswm_q, hunan<span class="sc">$</span>GDPPC)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>GDPPC.lag</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 24847.20 22724.80 24143.25 27737.50 27270.25 21248.80 43747.00 33582.71
 [9] 45651.17 32027.62 32671.00 20810.00 25711.50 30672.33 33457.75 31689.20
[17] 20269.00 23901.60 25126.17 21903.43 22718.60 25918.80 20307.00 20023.80
[25] 16576.80 18667.00 14394.67 19848.80 15516.33 20518.00 17572.00 15200.12
[33] 18413.80 14419.33 24094.50 22019.83 12923.50 14756.00 13869.80 12296.67
[41] 15775.17 14382.86 11566.33 13199.50 23412.00 39541.00 36186.60 16559.60
[49] 20772.50 19471.20 19827.33 15466.80 12925.67 18577.17 14943.00 24913.00
[57] 25093.00 24428.80 17003.00 21143.75 20435.00 17131.33 24569.75 23835.50
[65] 26360.00 47383.40 55157.75 37058.00 21546.67 23348.67 42323.67 28938.60
[73] 25880.80 47345.67 18711.33 29087.29 20748.29 35933.71 15439.71 29787.50
[81] 18145.00 21617.00 29203.89 41363.67 22259.09 44939.56 16902.00 16930.00</code></pre>
</div>
</div>
<p>In the earlier section, we retrieved the GDPPC of these five countries by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>nb1 <span class="ot">&lt;-</span> wm_q[[<span class="dv">1</span>]]</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>nb1 <span class="ot">&lt;-</span> hunan<span class="sc">$</span>GDPPC[nb1]</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>nb1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20981 34592 24473 21311 22879</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Question: Can you see the meaning of Spatial lag with row-standardized weights now?</p>
<p>The <strong>spatial lag with row-standardized weights</strong> helps quantify the average impact of neighboring regions on a specific variable (e.g., GDP per capita). It shows how a region’s characteristics, such as economic performance, are influenced by its neighbors, with the weights for each region’s neighbors summing to 1 for consistency across regions.</p>
<ul>
<li><p><strong>Spatial Lag</strong>: Represents the weighted average of a region’s neighbors’ values, with equal weight assigned to each neighbor in the row-standardized approach.</p></li>
<li><p><strong>Row-Standardized Weights</strong>: Since the sum of the weights for each region’s neighbors equals 1, the spatial lag becomes the arithmetic mean of its neighbors’ values. More neighbors dilute the influence of any single one.</p></li>
<li><p><strong>Practical Use</strong>: Spatial lag reflects how the GDP of neighboring regions affects a region’s own GDP. If there is a mismatch between a region’s GDP and that of its neighbors, this will be evident in the spatial lag, making it a valuable tool in spatial econometrics for understanding regional dynamics.</p></li>
</ul>
</div>
</div>
<p>Append the spatially lag GDPPC Values</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>lag.list <span class="ot">&lt;-</span> <span class="fu">list</span>(hunan<span class="sc">$</span>NAME_3, <span class="fu">lag.listw</span>(rswm_q, hunan<span class="sc">$</span>GDPPC))</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>lag.res <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(lag.list)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(lag.res) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"NAME_3"</span>, <span class="st">"lag GDPPC"</span>)</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>hunan <span class="ot">&lt;-</span> <span class="fu">left_join</span>(hunan,lag.res)</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(hunan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 36 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 110.4922 ymin: 28.61762 xmax: 112.3013 ymax: 30.12812
Geodetic CRS:  WGS 84
   NAME_2  ID_3  NAME_3   ENGTYPE_3 Shape_Leng Shape_Area  County    City
1 Changde 21098 Anxiang      County   1.869074 0.10056190 Anxiang Changde
2 Changde 21100 Hanshou      County   2.360691 0.19978745 Hanshou Changde
3 Changde 21101  Jinshi County City   1.425620 0.05302413  Jinshi Changde
4 Changde 21102      Li      County   3.474325 0.18908121      Li Changde
5 Changde 21103   Linli      County   2.289506 0.11450357   Linli Changde
6 Changde 21104  Shimen      County   4.171918 0.37194707  Shimen Changde
  avg_wage deposite     FAI Gov_Rev Gov_Exp     GDP GDPPC     GIO   Loan  NIPCR
1    31935   5517.2  3541.0  243.64  1779.5 12482.0 23667  5108.9 2806.9 7693.7
2    32265   7979.0  8665.0  386.13  2062.4 15788.0 20981 13491.0 4550.0 8269.9
3    28692   4581.7  4777.0  373.31  1148.4  8706.9 34592 10935.0 2242.0 8169.9
4    32541  13487.0 16066.0  709.61  2459.5 20322.0 24473 18402.0 6748.0 8377.0
5    32667    564.1  7781.2  336.86  1538.7 10355.0 25554  8214.0  358.0 8143.1
6    33261   8334.4 10531.0  548.33  2178.8 16293.0 27137 17795.0 6026.5 6156.0
   Bed    Emp  EmpR EmpRT Pri_Stu Sec_Stu Household Household_R NOIP Pop_R
1 1931 336.39 270.5 205.9  19.584  17.819     148.1       135.4   53 346.0
2 2560 456.78 388.8 246.7  42.097  33.029     240.2       208.7   95 553.2
3  848 122.78  82.1  61.7   8.723   7.592      81.9        43.7   77  92.4
4 2038 513.44 426.8 227.1  38.975  33.938     268.5       256.0   96 539.7
5 1440 307.36 272.2 100.8  23.286  18.943     129.1       157.2   99 246.6
6 2502 392.05 329.6 193.8  29.245  26.104     190.6       184.7  122 399.2
    RSCG Pop_T    Agri Service Disp_Inc      RORP    ROREmp lag GDPPC
1 3957.9 528.3 4524.41   14100    16610 0.6549309 0.8041262  24847.20
2 4460.5 804.6 6545.35   17727    18925 0.6875466 0.8511756  22724.80
3 3683.0 251.8 2562.46    7525    19498 0.3669579 0.6686757  24143.25
4 7110.2 832.5 7562.34   53160    18985 0.6482883 0.8312558  27737.50
5 3604.9 409.3 3583.91    7031    18604 0.6024921 0.8856065  27270.25
6 6490.7 600.5 5266.51    6981    19275 0.6647794 0.8407091  21248.80
                        geometry
1 POLYGON ((112.0625 29.75523...
2 POLYGON ((112.2288 29.11684...
3 POLYGON ((111.8927 29.6013,...
4 POLYGON ((111.3731 29.94649...
5 POLYGON ((111.6324 29.76288...
6 POLYGON ((110.8825 30.11675...</code></pre>
</div>
</div>
<p>Plot both GDPPC and spatial Lag GDPPC for comparison.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>gdppc <span class="ot">&lt;-</span> <span class="fu">qtm</span>(hunan, <span class="st">"GDPPC"</span>)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>lag_gdppc <span class="ot">&lt;-</span> <span class="fu">qtm</span>(hunan, <span class="st">"lag GDPPC"</span>)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(gdppc, lag_gdppc, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands_On_Exercise5_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="spatial-lag-as-a-sum-of-neighbouring-values" class="level2">
<h2 class="anchored" data-anchor-id="spatial-lag-as-a-sum-of-neighbouring-values">8.2 spatial lag as a sum of neighbouring values</h2>
<p>Calculating the <strong>spatial lag</strong> by summing the GDP per capita (GDPPC) values of neighboring regions. Unlike row-standardized weights, where each neighbor’s value is averaged, here each neighbor’s GDPPC is simply added up without adjusting for the number of neighbors (since <code>style = "B"</code> is used, indicating <strong>binary weights</strong>). This approach gives an unweighted sum of neighboring values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>b_weights <span class="ot">&lt;-</span> <span class="fu">lapply</span>(wm_q, <span class="cf">function</span>(x) <span class="dv">0</span><span class="sc">*</span>x <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>b_weights2 <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(wm_q, </span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">glist =</span> b_weights, </span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">style =</span> <span class="st">"B"</span>)</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>b_weights2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 88 
Number of nonzero links: 448 
Percentage nonzero weights: 5.785124 
Average number of links: 5.090909 

Weights style: B 
Weights constants summary:
   n   nn  S0  S1    S2
B 88 7744 448 896 10224</code></pre>
</div>
</div>
<ul>
<li><p><strong><code>b_weights</code></strong>: A binary weight matrix where each neighbor is assigned a weight of 1. The function <code>0*x + 1</code> ensures that for each neighbor, the weight is 1, no matter the distance or number of neighbors.</p></li>
<li><p><strong><code>b_weights2</code></strong>: Converts the neighbor list <code>wm_q</code> to a binary weight matrix, meaning all neighboring polygons are equally weighted with no standardization.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>lag_sum <span class="ot">&lt;-</span> <span class="fu">list</span>(hunan<span class="sc">$</span>NAME_3, <span class="fu">lag.listw</span>(b_weights2, hunan<span class="sc">$</span>GDPPC))</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>lag.res <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(lag_sum)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(lag.res) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"NAME_3"</span>, <span class="st">"lag_sum GDPPC"</span>)</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>lag_sum</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
 [1] "Anxiang"       "Hanshou"       "Jinshi"        "Li"           
 [5] "Linli"         "Shimen"        "Liuyang"       "Ningxiang"    
 [9] "Wangcheng"     "Anren"         "Guidong"       "Jiahe"        
[13] "Linwu"         "Rucheng"       "Yizhang"       "Yongxing"     
[17] "Zixing"        "Changning"     "Hengdong"      "Hengnan"      
[21] "Hengshan"      "Leiyang"       "Qidong"        "Chenxi"       
[25] "Zhongfang"     "Huitong"       "Jingzhou"      "Mayang"       
[29] "Tongdao"       "Xinhuang"      "Xupu"          "Yuanling"     
[33] "Zhijiang"      "Lengshuijiang" "Shuangfeng"    "Xinhua"       
[37] "Chengbu"       "Dongan"        "Dongkou"       "Longhui"      
[41] "Shaodong"      "Suining"       "Wugang"        "Xinning"      
[45] "Xinshao"       "Shaoshan"      "Xiangxiang"    "Baojing"      
[49] "Fenghuang"     "Guzhang"       "Huayuan"       "Jishou"       
[53] "Longshan"      "Luxi"          "Yongshun"      "Anhua"        
[57] "Nan"           "Yuanjiang"     "Jianghua"      "Lanshan"      
[61] "Ningyuan"      "Shuangpai"     "Xintian"       "Huarong"      
[65] "Linxiang"      "Miluo"         "Pingjiang"     "Xiangyin"     
[69] "Cili"          "Chaling"       "Liling"        "Yanling"      
[73] "You"           "Zhuzhou"       "Sangzhi"       "Yueyang"      
[77] "Qiyang"        "Taojiang"      "Shaoyang"      "Lianyuan"     
[81] "Hongjiang"     "Hengyang"      "Guiyang"       "Changsha"     
[85] "Taoyuan"       "Xiangtan"      "Dao"           "Jiangyong"    

[[2]]
 [1] 124236 113624  96573 110950 109081 106244 174988 235079 273907 256221
[11]  98013 104050 102846  92017 133831 158446 141883 119508 150757 153324
[21] 113593 129594 142149 100119  82884  74668  43184  99244  46549  20518
[31] 140576 121601  92069  43258 144567 132119  51694  59024  69349  73780
[41]  94651 100680  69398  52798 140472 118623 180933  82798  83090  97356
[51]  59482  77334  38777 111463  74715 174391 150558 122144  68012  84575
[61] 143045  51394  98279  47671  26360 236917 220631 185290  64640  70046
[71] 126971 144693 129404 284074 112268 203611 145238 251536 108078 238300
[81] 108870 108085 262835 248182 244850 404456  67608  33860</code></pre>
</div>
</div>
<ul>
<li><p><strong><code>lag.listw(b_weights2, hunan$GDPPC)</code></strong>: This function calculates the <strong>spatial lag</strong> as the <strong>sum of GDPPC values</strong> of neighboring regions based on the binary weights. It returns a vector of summed GDPPC values for each region.</p></li>
<li><p><strong><code>lag_sum</code></strong>: Combines the region names (<code>hunan$NAME_3</code>) with the spatial lag values (summed GDPPC) into a list.</p></li>
<li><p><strong><code>lag.res</code></strong>: Converts this list into a data frame and assigns appropriate column names (“NAME_3” and “lag_sum GDPPC”).</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Question: Can you understand the meaning of Spatial lag as a sum of neighboring values now?</p>
<p>This method of calculating spatial lag highlights the <strong>cumulative economic influence</strong> of neighboring regions. Regions with more neighbors will tend to have larger summed values, whereas regions with fewer neighbors may have lower sums, which can be important when considering spatial spillover effects.</p>
<ul>
<li><p><strong>Spatial Lag as a Sum</strong>: In this approach, the spatial lag is the <strong>sum of the GDPPC values</strong> of a region’s neighbors. Unlike row-standardized weights where values are averaged, here each neighbor’s GDPPC is simply added up, emphasizing the total contribution from neighboring regions.</p></li>
<li><p><strong>Example</strong>: If a region has three neighbors with GDPPC values of 20000, 25000, and 30000, the spatial lag would be the sum of these values: 20000+25000+30000=7500020000 + 25000 + 30000 = 7500020000+25000+30000=75000.</p></li>
</ul>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>hunan <span class="ot">&lt;-</span> <span class="fu">left_join</span>(hunan, lag.res)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>gdppc <span class="ot">&lt;-</span> <span class="fu">qtm</span>(hunan, <span class="st">"GDPPC"</span>)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>lag_sum_gdppc <span class="ot">&lt;-</span> <span class="fu">qtm</span>(hunan, <span class="st">"lag_sum GDPPC"</span>)</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(gdppc, lag_sum_gdppc, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands_On_Exercise5_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="spatial-window-average" class="level2">
<h2 class="anchored" data-anchor-id="spatial-window-average">8.3 spatial window average</h2>
<p>modifying the neighbor structure to include each polygon itself as its own neighbor (i.e., adding a diagonal element), followed by computing the spatial lag of the GDPPC (Gross Domestic Product Per Capita) for each region, and finally visualizing and comparing the results.</p>
<section id="include-self-in-neighbor-list" class="level3">
<h3 class="anchored" data-anchor-id="include-self-in-neighbor-list">8.3.1. <strong>Include Self in Neighbor List</strong>:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>wm_qs <span class="ot">&lt;-</span> <span class="fu">include.self</span>(wm_q)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>wm_qs[[<span class="dv">1</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  1  2  3  4 57 85</code></pre>
</div>
</div>
<ul>
<li><p><strong><code>include.self(wm_q)</code></strong>: This function adds the diagonal element to the neighbor list, meaning that each region is now considered its own neighbor, in addition to its original neighbors.</p>
<ul>
<li>For example, if region 1 originally had neighbors 2 and 3, after using <code>include.self()</code>, region 1 will now also be its own neighbor.</li>
</ul></li>
<li><p><strong><code>wm_qs[[1]]</code></strong>: Displays the neighbors of region 1, which now includes itself.</p></li>
</ul>
</section>
<section id="convert-to-weights-list" class="level3">
<h3 class="anchored" data-anchor-id="convert-to-weights-list">8.3.2. <strong>Convert to Weights List</strong>:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>wm_qs <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(wm_qs)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>wm_qs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 88 
Number of nonzero links: 536 
Percentage nonzero weights: 6.921488 
Average number of links: 6.090909 

Weights style: W 
Weights constants summary:
   n   nn S0       S1       S2
W 88 7744 88 30.90265 357.5308</code></pre>
</div>
</div>
<ul>
<li><p><strong><code>nb2listw(wm_qs)</code></strong>: Converts the updated neighbor list (with diagonal elements) into a <strong>weights list</strong>. This weights list will now include self-influence (i.e., each region is also its own neighbor with a certain weight).</p></li>
<li><p><strong>Weights List</strong>: The resulting object stores the spatial weights for each region based on its new neighbor structure (including itself).</p></li>
</ul>
</section>
<section id="calculate-spatial-lag-with-self" class="level3">
<h3 class="anchored" data-anchor-id="calculate-spatial-lag-with-self">8.3.3 <strong>Calculate Spatial Lag (with Self)</strong>:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>lag_w_avg_gpdpc <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(wm_qs, hunan<span class="sc">$</span>GDPPC)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>lag_w_avg_gpdpc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 24650.50 22434.17 26233.00 27084.60 26927.00 22230.17 47621.20 37160.12
 [9] 49224.71 29886.89 26627.50 22690.17 25366.40 25825.75 30329.00 32682.83
[17] 25948.62 23987.67 25463.14 21904.38 23127.50 25949.83 20018.75 19524.17
[25] 18955.00 17800.40 15883.00 18831.33 14832.50 17965.00 17159.89 16199.44
[33] 18764.50 26878.75 23188.86 20788.14 12365.20 15985.00 13764.83 11907.43
[41] 17128.14 14593.62 11644.29 12706.00 21712.29 43548.25 35049.00 16226.83
[49] 19294.40 18156.00 19954.75 18145.17 12132.75 18419.29 14050.83 23619.75
[57] 24552.71 24733.67 16762.60 20932.60 19467.75 18334.00 22541.00 26028.00
[65] 29128.50 46569.00 47576.60 36545.50 20838.50 22531.00 42115.50 27619.00
[73] 27611.33 44523.29 18127.43 28746.38 20734.50 33880.62 14716.38 28516.22
[81] 18086.14 21244.50 29568.80 48119.71 22310.75 43151.60 17133.40 17009.33</code></pre>
</div>
</div>
<p><strong><code>lag.listw(wm_qs, hunan$GDPPC)</code></strong>: Computes the <strong>spatial lag</strong> of the GDPPC values using the updated weights list (<code>wm_qs</code>). The spatial lag now includes the influence of the region itself, in addition to its neighbors.</p>
<ul>
<li>This means that when calculating the spatial lag for a region, its own GDPPC value is considered in the weighted average along with its neighbors’ values.</li>
</ul>
</section>
<section id="store-results-and-modify-data" class="level3">
<h3 class="anchored" data-anchor-id="store-results-and-modify-data">8.3.4. <strong>Store Results and Modify Data</strong>:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>lag.list.wm_qs <span class="ot">&lt;-</span> <span class="fu">list</span>(hunan<span class="sc">$</span>NAME_3, <span class="fu">lag.listw</span>(wm_qs, hunan<span class="sc">$</span>GDPPC))</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>lag_wm_qs.res <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(lag.list.wm_qs)</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(lag_wm_qs.res) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"NAME_3"</span>, <span class="st">"lag_window_avg GDPPC"</span>)</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>hunan <span class="ot">&lt;-</span> <span class="fu">left_join</span>(hunan, lag_wm_qs.res)</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>hunan <span class="sc">%&gt;%</span></span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"County"</span>, <span class="st">"lag GDPPC"</span>, <span class="st">"lag_window_avg GDPPC"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 13%">
<col style="width: 27%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">lag GDPPC</th>
<th style="text-align: right;">lag_window_avg GDPPC</th>
<th style="text-align: left;">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Anxiang</td>
<td style="text-align: right;">24847.20</td>
<td style="text-align: right;">24650.50</td>
<td style="text-align: left;">POLYGON ((112.0625 29.75523…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hanshou</td>
<td style="text-align: right;">22724.80</td>
<td style="text-align: right;">22434.17</td>
<td style="text-align: left;">POLYGON ((112.2288 29.11684…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jinshi</td>
<td style="text-align: right;">24143.25</td>
<td style="text-align: right;">26233.00</td>
<td style="text-align: left;">POLYGON ((111.8927 29.6013,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Li</td>
<td style="text-align: right;">27737.50</td>
<td style="text-align: right;">27084.60</td>
<td style="text-align: left;">POLYGON ((111.3731 29.94649…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Linli</td>
<td style="text-align: right;">27270.25</td>
<td style="text-align: right;">26927.00</td>
<td style="text-align: left;">POLYGON ((111.6324 29.76288…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shimen</td>
<td style="text-align: right;">21248.80</td>
<td style="text-align: right;">22230.17</td>
<td style="text-align: left;">POLYGON ((110.8825 30.11675…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Liuyang</td>
<td style="text-align: right;">43747.00</td>
<td style="text-align: right;">47621.20</td>
<td style="text-align: left;">POLYGON ((113.9905 28.5682,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ningxiang</td>
<td style="text-align: right;">33582.71</td>
<td style="text-align: right;">37160.12</td>
<td style="text-align: left;">POLYGON ((112.7181 28.38299…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wangcheng</td>
<td style="text-align: right;">45651.17</td>
<td style="text-align: right;">49224.71</td>
<td style="text-align: left;">POLYGON ((112.7914 28.52688…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anren</td>
<td style="text-align: right;">32027.62</td>
<td style="text-align: right;">29886.89</td>
<td style="text-align: left;">POLYGON ((113.1757 26.82734…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Guidong</td>
<td style="text-align: right;">32671.00</td>
<td style="text-align: right;">26627.50</td>
<td style="text-align: left;">POLYGON ((114.1799 26.20117…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jiahe</td>
<td style="text-align: right;">20810.00</td>
<td style="text-align: right;">22690.17</td>
<td style="text-align: left;">POLYGON ((112.4425 25.74358…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Linwu</td>
<td style="text-align: right;">25711.50</td>
<td style="text-align: right;">25366.40</td>
<td style="text-align: left;">POLYGON ((112.5914 25.55143…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rucheng</td>
<td style="text-align: right;">30672.33</td>
<td style="text-align: right;">25825.75</td>
<td style="text-align: left;">POLYGON ((113.6759 25.87578…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yizhang</td>
<td style="text-align: right;">33457.75</td>
<td style="text-align: right;">30329.00</td>
<td style="text-align: left;">POLYGON ((113.2621 25.68394…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yongxing</td>
<td style="text-align: right;">31689.20</td>
<td style="text-align: right;">32682.83</td>
<td style="text-align: left;">POLYGON ((113.3169 26.41843…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zixing</td>
<td style="text-align: right;">20269.00</td>
<td style="text-align: right;">25948.62</td>
<td style="text-align: left;">POLYGON ((113.7311 26.16259…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Changning</td>
<td style="text-align: right;">23901.60</td>
<td style="text-align: right;">23987.67</td>
<td style="text-align: left;">POLYGON ((112.6144 26.60198…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hengdong</td>
<td style="text-align: right;">25126.17</td>
<td style="text-align: right;">25463.14</td>
<td style="text-align: left;">POLYGON ((113.1056 27.21007…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hengnan</td>
<td style="text-align: right;">21903.43</td>
<td style="text-align: right;">21904.38</td>
<td style="text-align: left;">POLYGON ((112.7599 26.98149…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hengshan</td>
<td style="text-align: right;">22718.60</td>
<td style="text-align: right;">23127.50</td>
<td style="text-align: left;">POLYGON ((112.607 27.4689, …</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leiyang</td>
<td style="text-align: right;">25918.80</td>
<td style="text-align: right;">25949.83</td>
<td style="text-align: left;">POLYGON ((112.9996 26.69276…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Qidong</td>
<td style="text-align: right;">20307.00</td>
<td style="text-align: right;">20018.75</td>
<td style="text-align: left;">POLYGON ((111.7818 27.0383,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chenxi</td>
<td style="text-align: right;">20023.80</td>
<td style="text-align: right;">19524.17</td>
<td style="text-align: left;">POLYGON ((110.2624 28.21778…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zhongfang</td>
<td style="text-align: right;">16576.80</td>
<td style="text-align: right;">18955.00</td>
<td style="text-align: left;">POLYGON ((109.9431 27.72858…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Huitong</td>
<td style="text-align: right;">18667.00</td>
<td style="text-align: right;">17800.40</td>
<td style="text-align: left;">POLYGON ((109.9419 27.10512…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jingzhou</td>
<td style="text-align: right;">14394.67</td>
<td style="text-align: right;">15883.00</td>
<td style="text-align: left;">POLYGON ((109.8186 26.75842…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mayang</td>
<td style="text-align: right;">19848.80</td>
<td style="text-align: right;">18831.33</td>
<td style="text-align: left;">POLYGON ((109.795 27.98008,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tongdao</td>
<td style="text-align: right;">15516.33</td>
<td style="text-align: right;">14832.50</td>
<td style="text-align: left;">POLYGON ((109.9294 26.46561…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xinhuang</td>
<td style="text-align: right;">20518.00</td>
<td style="text-align: right;">17965.00</td>
<td style="text-align: left;">POLYGON ((109.227 27.43733,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xupu</td>
<td style="text-align: right;">17572.00</td>
<td style="text-align: right;">17159.89</td>
<td style="text-align: left;">POLYGON ((110.7189 28.30485…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yuanling</td>
<td style="text-align: right;">15200.12</td>
<td style="text-align: right;">16199.44</td>
<td style="text-align: left;">POLYGON ((110.9652 28.99895…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zhijiang</td>
<td style="text-align: right;">18413.80</td>
<td style="text-align: right;">18764.50</td>
<td style="text-align: left;">POLYGON ((109.8818 27.60661…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lengshuijiang</td>
<td style="text-align: right;">14419.33</td>
<td style="text-align: right;">26878.75</td>
<td style="text-align: left;">POLYGON ((111.5307 27.81472…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shuangfeng</td>
<td style="text-align: right;">24094.50</td>
<td style="text-align: right;">23188.86</td>
<td style="text-align: left;">POLYGON ((112.263 27.70421,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xinhua</td>
<td style="text-align: right;">22019.83</td>
<td style="text-align: right;">20788.14</td>
<td style="text-align: left;">POLYGON ((111.3345 28.19642…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chengbu</td>
<td style="text-align: right;">12923.50</td>
<td style="text-align: right;">12365.20</td>
<td style="text-align: left;">POLYGON ((110.4455 26.69317…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dongan</td>
<td style="text-align: right;">14756.00</td>
<td style="text-align: right;">15985.00</td>
<td style="text-align: left;">POLYGON ((111.4531 26.86812…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dongkou</td>
<td style="text-align: right;">13869.80</td>
<td style="text-align: right;">13764.83</td>
<td style="text-align: left;">POLYGON ((110.6622 27.37305…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Longhui</td>
<td style="text-align: right;">12296.67</td>
<td style="text-align: right;">11907.43</td>
<td style="text-align: left;">POLYGON ((110.985 27.65983,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shaodong</td>
<td style="text-align: right;">15775.17</td>
<td style="text-align: right;">17128.14</td>
<td style="text-align: left;">POLYGON ((111.9054 27.40254…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Suining</td>
<td style="text-align: right;">14382.86</td>
<td style="text-align: right;">14593.62</td>
<td style="text-align: left;">POLYGON ((110.389 27.10006,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wugang</td>
<td style="text-align: right;">11566.33</td>
<td style="text-align: right;">11644.29</td>
<td style="text-align: left;">POLYGON ((110.9878 27.03345…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xinning</td>
<td style="text-align: right;">13199.50</td>
<td style="text-align: right;">12706.00</td>
<td style="text-align: left;">POLYGON ((111.0736 26.84627…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xinshao</td>
<td style="text-align: right;">23412.00</td>
<td style="text-align: right;">21712.29</td>
<td style="text-align: left;">POLYGON ((111.6013 27.58275…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shaoshan</td>
<td style="text-align: right;">39541.00</td>
<td style="text-align: right;">43548.25</td>
<td style="text-align: left;">POLYGON ((112.5391 27.97742…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xiangxiang</td>
<td style="text-align: right;">36186.60</td>
<td style="text-align: right;">35049.00</td>
<td style="text-align: left;">POLYGON ((112.4549 28.05783…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Baojing</td>
<td style="text-align: right;">16559.60</td>
<td style="text-align: right;">16226.83</td>
<td style="text-align: left;">POLYGON ((109.7015 28.82844…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fenghuang</td>
<td style="text-align: right;">20772.50</td>
<td style="text-align: right;">19294.40</td>
<td style="text-align: left;">POLYGON ((109.5239 28.19206…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Guzhang</td>
<td style="text-align: right;">19471.20</td>
<td style="text-align: right;">18156.00</td>
<td style="text-align: left;">POLYGON ((109.8968 28.74034…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Huayuan</td>
<td style="text-align: right;">19827.33</td>
<td style="text-align: right;">19954.75</td>
<td style="text-align: left;">POLYGON ((109.5647 28.61712…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jishou</td>
<td style="text-align: right;">15466.80</td>
<td style="text-align: right;">18145.17</td>
<td style="text-align: left;">POLYGON ((109.8375 28.4696,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Longshan</td>
<td style="text-align: right;">12925.67</td>
<td style="text-align: right;">12132.75</td>
<td style="text-align: left;">POLYGON ((109.6337 29.62521…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Luxi</td>
<td style="text-align: right;">18577.17</td>
<td style="text-align: right;">18419.29</td>
<td style="text-align: left;">POLYGON ((110.1067 28.41835…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yongshun</td>
<td style="text-align: right;">14943.00</td>
<td style="text-align: right;">14050.83</td>
<td style="text-align: left;">POLYGON ((110.0003 29.29499…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anhua</td>
<td style="text-align: right;">24913.00</td>
<td style="text-align: right;">23619.75</td>
<td style="text-align: left;">POLYGON ((111.6034 28.63716…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nan</td>
<td style="text-align: right;">25093.00</td>
<td style="text-align: right;">24552.71</td>
<td style="text-align: left;">POLYGON ((112.3232 29.46074…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yuanjiang</td>
<td style="text-align: right;">24428.80</td>
<td style="text-align: right;">24733.67</td>
<td style="text-align: left;">POLYGON ((112.4391 29.1791,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jianghua</td>
<td style="text-align: right;">17003.00</td>
<td style="text-align: right;">16762.60</td>
<td style="text-align: left;">POLYGON ((111.6461 25.29661…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lanshan</td>
<td style="text-align: right;">21143.75</td>
<td style="text-align: right;">20932.60</td>
<td style="text-align: left;">POLYGON ((112.2286 25.61123…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ningyuan</td>
<td style="text-align: right;">20435.00</td>
<td style="text-align: right;">19467.75</td>
<td style="text-align: left;">POLYGON ((112.0715 26.09892…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shuangpai</td>
<td style="text-align: right;">17131.33</td>
<td style="text-align: right;">18334.00</td>
<td style="text-align: left;">POLYGON ((111.8864 26.11957…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xintian</td>
<td style="text-align: right;">24569.75</td>
<td style="text-align: right;">22541.00</td>
<td style="text-align: left;">POLYGON ((112.2578 26.0796,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Huarong</td>
<td style="text-align: right;">23835.50</td>
<td style="text-align: right;">26028.00</td>
<td style="text-align: left;">POLYGON ((112.9242 29.69134…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Linxiang</td>
<td style="text-align: right;">26360.00</td>
<td style="text-align: right;">29128.50</td>
<td style="text-align: left;">POLYGON ((113.5502 29.67418…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Miluo</td>
<td style="text-align: right;">47383.40</td>
<td style="text-align: right;">46569.00</td>
<td style="text-align: left;">POLYGON ((112.9902 29.02139…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pingjiang</td>
<td style="text-align: right;">55157.75</td>
<td style="text-align: right;">47576.60</td>
<td style="text-align: left;">POLYGON ((113.8436 29.06152…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xiangyin</td>
<td style="text-align: right;">37058.00</td>
<td style="text-align: right;">36545.50</td>
<td style="text-align: left;">POLYGON ((112.9173 28.98264…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cili</td>
<td style="text-align: right;">21546.67</td>
<td style="text-align: right;">20838.50</td>
<td style="text-align: left;">POLYGON ((110.8822 29.69017…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chaling</td>
<td style="text-align: right;">23348.67</td>
<td style="text-align: right;">22531.00</td>
<td style="text-align: left;">POLYGON ((113.7666 27.10573…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Liling</td>
<td style="text-align: right;">42323.67</td>
<td style="text-align: right;">42115.50</td>
<td style="text-align: left;">POLYGON ((113.5673 27.94346…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yanling</td>
<td style="text-align: right;">28938.60</td>
<td style="text-align: right;">27619.00</td>
<td style="text-align: left;">POLYGON ((113.9292 26.6154,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">You</td>
<td style="text-align: right;">25880.80</td>
<td style="text-align: right;">27611.33</td>
<td style="text-align: left;">POLYGON ((113.5879 27.41324…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zhuzhou</td>
<td style="text-align: right;">47345.67</td>
<td style="text-align: right;">44523.29</td>
<td style="text-align: left;">POLYGON ((113.2493 28.02411…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sangzhi</td>
<td style="text-align: right;">18711.33</td>
<td style="text-align: right;">18127.43</td>
<td style="text-align: left;">POLYGON ((110.556 29.40543,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yueyang</td>
<td style="text-align: right;">29087.29</td>
<td style="text-align: right;">28746.38</td>
<td style="text-align: left;">POLYGON ((113.343 29.61064,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Qiyang</td>
<td style="text-align: right;">20748.29</td>
<td style="text-align: right;">20734.50</td>
<td style="text-align: left;">POLYGON ((111.5563 26.81318…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Taojiang</td>
<td style="text-align: right;">35933.71</td>
<td style="text-align: right;">33880.62</td>
<td style="text-align: left;">POLYGON ((112.0508 28.67265…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shaoyang</td>
<td style="text-align: right;">15439.71</td>
<td style="text-align: right;">14716.38</td>
<td style="text-align: left;">POLYGON ((111.5013 27.30207…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lianyuan</td>
<td style="text-align: right;">29787.50</td>
<td style="text-align: right;">28516.22</td>
<td style="text-align: left;">POLYGON ((111.6789 28.02946…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hongjiang</td>
<td style="text-align: right;">18145.00</td>
<td style="text-align: right;">18086.14</td>
<td style="text-align: left;">POLYGON ((110.1441 27.47513…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hengyang</td>
<td style="text-align: right;">21617.00</td>
<td style="text-align: right;">21244.50</td>
<td style="text-align: left;">POLYGON ((112.7144 26.98613…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Guiyang</td>
<td style="text-align: right;">29203.89</td>
<td style="text-align: right;">29568.80</td>
<td style="text-align: left;">POLYGON ((113.0811 26.04963…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Changsha</td>
<td style="text-align: right;">41363.67</td>
<td style="text-align: right;">48119.71</td>
<td style="text-align: left;">POLYGON ((112.9421 28.03722…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Taoyuan</td>
<td style="text-align: right;">22259.09</td>
<td style="text-align: right;">22310.75</td>
<td style="text-align: left;">POLYGON ((112.0612 29.32855…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xiangtan</td>
<td style="text-align: right;">44939.56</td>
<td style="text-align: right;">43151.60</td>
<td style="text-align: left;">POLYGON ((113.0426 27.8942,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dao</td>
<td style="text-align: right;">16902.00</td>
<td style="text-align: right;">17133.40</td>
<td style="text-align: left;">POLYGON ((111.498 25.81679,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jiangyong</td>
<td style="text-align: right;">16930.00</td>
<td style="text-align: right;">17009.33</td>
<td style="text-align: left;">POLYGON ((111.3659 25.39472…</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li><p><strong>Store Lag Results</strong>: A new list, <code>lag.list.wm_qs</code>, is created to store the names of the regions (<code>hunan$NAME_3</code>) and their corresponding spatial lag values.</p></li>
<li><p><strong>Convert to Data Frame</strong>: The list is converted into a data frame (<code>lag_wm_qs.res</code>), where each row contains a region’s name and its calculated spatial lag (including self).</p></li>
<li><p><strong>Column Names</strong>: The columns are renamed for clarity, with <code>lag_window_avg GDPPC</code> indicating the spatial lag values, including the diagonal elements (self).</p></li>
</ul>
</section>
<section id="visualize-the-results-and-interpret" class="level3">
<h3 class="anchored" data-anchor-id="visualize-the-results-and-interpret"><strong>8.3.5 Visualize the Results</strong>: and Interpret</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>w_avg_gdppc <span class="ot">&lt;-</span> <span class="fu">qtm</span>(hunan, <span class="st">"lag_window_avg GDPPC"</span>)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(lag_gdppc, w_avg_gdppc, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands_On_Exercise5_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><strong>Adding Self as a Neighbor</strong>: The code includes each region as its own neighbor, which means when calculating the spatial lag (the weighted average of neighboring values), the region’s own value is now part of the calculation.</p></li>
<li><p><strong>Spatial Lag Comparison</strong>: Two versions of the spatial lag are created:</p>
<ul>
<li><p><strong>Without self</strong>: The original spatial lag where only neighboring regions influence the lagged value.</p></li>
<li><p><strong>With self</strong>: The spatial lag that includes the region’s own value in the weighted average.</p></li>
</ul></li>
</ul>
</section>
</section>
<section id="spatial-window-sum" class="level2">
<h2 class="anchored" data-anchor-id="spatial-window-sum">8.4 spatial window sum</h2>
<p>The <strong>spatial window sum</strong> calculates the sum of neighboring values for each region <strong>without using row-standardized weights</strong>. Unlike row-standardized weights, where each neighbor’s influence is normalized to ensure that the weights sum to 1, the spatial window sum uses <strong>binary weights</strong> (equal weight for each neighbor) but directly sums the values of the neighboring regions, including the region itself as its own neighbor (with the help of <code>include.self()</code>).</p>
<section id="add-diagonal-element-include-self-as-neighbor" class="level3">
<h3 class="anchored" data-anchor-id="add-diagonal-element-include-self-as-neighbor">8.4.1 <strong>Add Diagonal Element (Include Self as Neighbor)</strong>:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>wm_qs <span class="ot">&lt;-</span> <span class="fu">include.self</span>(wm_q)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>wm_qs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 88 
Number of nonzero links: 536 
Percentage nonzero weights: 6.921488 
Average number of links: 6.090909 </code></pre>
</div>
</div>
<p><strong><code>include.self(wm_q)</code></strong>: This function modifies the neighbor list (<code>wm_q</code>) so that each region now considers itself as one of its neighbors. This allows the region’s own GDPPC value to be included when calculating the spatial sum</p>
</section>
<section id="create-binary-weights-convert-neighbor-to-weight-matrix" class="level3">
<h3 class="anchored" data-anchor-id="create-binary-weights-convert-neighbor-to-weight-matrix">8.4.2 <strong>Create Binary Weights</strong>: &amp; Convert Neighbor to weight matrix</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>b_weights <span class="ot">&lt;-</span> <span class="fu">lapply</span>(wm_qs, <span class="cf">function</span>(x) <span class="dv">0</span><span class="sc">*</span>x <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>b_weights[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 1 1 1 1 1 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>b_weights2 <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(wm_qs, <span class="at">glist =</span> b_weights, <span class="at">style =</span> <span class="st">"B"</span>)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>b_weights2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 88 
Number of nonzero links: 536 
Percentage nonzero weights: 6.921488 
Average number of links: 6.090909 

Weights style: B 
Weights constants summary:
   n   nn  S0   S1    S2
B 88 7744 536 1072 14160</code></pre>
</div>
</div>
<ul>
<li><p><strong><code>lapply(wm_qs, function(x) 0*x + 1)</code></strong>: This creates <strong>binary weights</strong>, where each neighbor, including the region itself, is given a weight of 1. This means that when calculating the spatial sum, each neighboring region’s GDPPC is added without adjusting for the number of neighbors.</p></li>
<li><p><strong>Example of <code>b_weights[1]</code></strong>: For the first region, this shows the binary weights assigned to its neighbors, which will all be 1 (since <code>0*x + 1</code> results in 1 for each neighbor).</p></li>
<li><p><strong><code>nb2listw(wm_qs, glist = b_weights, style = "B")</code></strong>: Converts the neighbor list with binary weights (<code>b_weights</code>) into a <strong>spatial weight matrix</strong>.</p>
<ul>
<li><p><strong><code>style = "B"</code></strong> means the matrix is <strong>binary</strong> (each neighbor gets an equal weight of 1).</p></li>
<li><p>This weight matrix is used to calculate the spatial window sum, where each neighboring region’s value is simply summed up.</p></li>
</ul></li>
</ul>
</section>
<section id="calculate-spatial-window-sum-for-gdppc" class="level3">
<h3 class="anchored" data-anchor-id="calculate-spatial-window-sum-for-gdppc">8.4.3 <strong>Calculate Spatial Window Sum for GDPPC</strong>:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>w_sum_gdppc <span class="ot">&lt;-</span> <span class="fu">list</span>(hunan<span class="sc">$</span>NAME_3, <span class="fu">lag.listw</span>(b_weights2, hunan<span class="sc">$</span>GDPPC))</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>w_sum_gdppc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
 [1] "Anxiang"       "Hanshou"       "Jinshi"        "Li"           
 [5] "Linli"         "Shimen"        "Liuyang"       "Ningxiang"    
 [9] "Wangcheng"     "Anren"         "Guidong"       "Jiahe"        
[13] "Linwu"         "Rucheng"       "Yizhang"       "Yongxing"     
[17] "Zixing"        "Changning"     "Hengdong"      "Hengnan"      
[21] "Hengshan"      "Leiyang"       "Qidong"        "Chenxi"       
[25] "Zhongfang"     "Huitong"       "Jingzhou"      "Mayang"       
[29] "Tongdao"       "Xinhuang"      "Xupu"          "Yuanling"     
[33] "Zhijiang"      "Lengshuijiang" "Shuangfeng"    "Xinhua"       
[37] "Chengbu"       "Dongan"        "Dongkou"       "Longhui"      
[41] "Shaodong"      "Suining"       "Wugang"        "Xinning"      
[45] "Xinshao"       "Shaoshan"      "Xiangxiang"    "Baojing"      
[49] "Fenghuang"     "Guzhang"       "Huayuan"       "Jishou"       
[53] "Longshan"      "Luxi"          "Yongshun"      "Anhua"        
[57] "Nan"           "Yuanjiang"     "Jianghua"      "Lanshan"      
[61] "Ningyuan"      "Shuangpai"     "Xintian"       "Huarong"      
[65] "Linxiang"      "Miluo"         "Pingjiang"     "Xiangyin"     
[69] "Cili"          "Chaling"       "Liling"        "Yanling"      
[73] "You"           "Zhuzhou"       "Sangzhi"       "Yueyang"      
[77] "Qiyang"        "Taojiang"      "Shaoyang"      "Lianyuan"     
[81] "Hongjiang"     "Hengyang"      "Guiyang"       "Changsha"     
[85] "Taoyuan"       "Xiangtan"      "Dao"           "Jiangyong"    

[[2]]
 [1] 147903 134605 131165 135423 134635 133381 238106 297281 344573 268982
[11] 106510 136141 126832 103303 151645 196097 207589 143926 178242 175235
[21] 138765 155699 160150 117145 113730  89002  63532 112988  59330  35930
[31] 154439 145795 112587 107515 162322 145517  61826  79925  82589  83352
[41] 119897 116749  81510  63530 151986 174193 210294  97361  96472 108936
[51]  79819 108871  48531 128935  84305 188958 171869 148402  83813 104663
[61] 155742  73336 112705  78084  58257 279414 237883 219273  83354  90124
[71] 168462 165714 165668 311663 126892 229971 165876 271045 117731 256646
[81] 126603 127467 295688 336838 267729 431516  85667  51028</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>w_sum_gdppc.res <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(w_sum_gdppc)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(w_sum_gdppc.res) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"NAME_3"</span>, <span class="st">"w_sum GDPPC"</span>)</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>hunan <span class="ot">&lt;-</span> <span class="fu">left_join</span>(hunan, w_sum_gdppc.res)</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>hunan <span class="sc">%&gt;%</span></span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"County"</span>, <span class="st">"lag_sum GDPPC"</span>, <span class="st">"w_sum GDPPC"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 16%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">lag_sum GDPPC</th>
<th style="text-align: right;">w_sum GDPPC</th>
<th style="text-align: left;">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Anxiang</td>
<td style="text-align: right;">124236</td>
<td style="text-align: right;">147903</td>
<td style="text-align: left;">POLYGON ((112.0625 29.75523…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hanshou</td>
<td style="text-align: right;">113624</td>
<td style="text-align: right;">134605</td>
<td style="text-align: left;">POLYGON ((112.2288 29.11684…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jinshi</td>
<td style="text-align: right;">96573</td>
<td style="text-align: right;">131165</td>
<td style="text-align: left;">POLYGON ((111.8927 29.6013,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Li</td>
<td style="text-align: right;">110950</td>
<td style="text-align: right;">135423</td>
<td style="text-align: left;">POLYGON ((111.3731 29.94649…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Linli</td>
<td style="text-align: right;">109081</td>
<td style="text-align: right;">134635</td>
<td style="text-align: left;">POLYGON ((111.6324 29.76288…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shimen</td>
<td style="text-align: right;">106244</td>
<td style="text-align: right;">133381</td>
<td style="text-align: left;">POLYGON ((110.8825 30.11675…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Liuyang</td>
<td style="text-align: right;">174988</td>
<td style="text-align: right;">238106</td>
<td style="text-align: left;">POLYGON ((113.9905 28.5682,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ningxiang</td>
<td style="text-align: right;">235079</td>
<td style="text-align: right;">297281</td>
<td style="text-align: left;">POLYGON ((112.7181 28.38299…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wangcheng</td>
<td style="text-align: right;">273907</td>
<td style="text-align: right;">344573</td>
<td style="text-align: left;">POLYGON ((112.7914 28.52688…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anren</td>
<td style="text-align: right;">256221</td>
<td style="text-align: right;">268982</td>
<td style="text-align: left;">POLYGON ((113.1757 26.82734…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Guidong</td>
<td style="text-align: right;">98013</td>
<td style="text-align: right;">106510</td>
<td style="text-align: left;">POLYGON ((114.1799 26.20117…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jiahe</td>
<td style="text-align: right;">104050</td>
<td style="text-align: right;">136141</td>
<td style="text-align: left;">POLYGON ((112.4425 25.74358…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Linwu</td>
<td style="text-align: right;">102846</td>
<td style="text-align: right;">126832</td>
<td style="text-align: left;">POLYGON ((112.5914 25.55143…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rucheng</td>
<td style="text-align: right;">92017</td>
<td style="text-align: right;">103303</td>
<td style="text-align: left;">POLYGON ((113.6759 25.87578…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yizhang</td>
<td style="text-align: right;">133831</td>
<td style="text-align: right;">151645</td>
<td style="text-align: left;">POLYGON ((113.2621 25.68394…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yongxing</td>
<td style="text-align: right;">158446</td>
<td style="text-align: right;">196097</td>
<td style="text-align: left;">POLYGON ((113.3169 26.41843…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zixing</td>
<td style="text-align: right;">141883</td>
<td style="text-align: right;">207589</td>
<td style="text-align: left;">POLYGON ((113.7311 26.16259…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Changning</td>
<td style="text-align: right;">119508</td>
<td style="text-align: right;">143926</td>
<td style="text-align: left;">POLYGON ((112.6144 26.60198…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hengdong</td>
<td style="text-align: right;">150757</td>
<td style="text-align: right;">178242</td>
<td style="text-align: left;">POLYGON ((113.1056 27.21007…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hengnan</td>
<td style="text-align: right;">153324</td>
<td style="text-align: right;">175235</td>
<td style="text-align: left;">POLYGON ((112.7599 26.98149…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hengshan</td>
<td style="text-align: right;">113593</td>
<td style="text-align: right;">138765</td>
<td style="text-align: left;">POLYGON ((112.607 27.4689, …</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leiyang</td>
<td style="text-align: right;">129594</td>
<td style="text-align: right;">155699</td>
<td style="text-align: left;">POLYGON ((112.9996 26.69276…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Qidong</td>
<td style="text-align: right;">142149</td>
<td style="text-align: right;">160150</td>
<td style="text-align: left;">POLYGON ((111.7818 27.0383,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chenxi</td>
<td style="text-align: right;">100119</td>
<td style="text-align: right;">117145</td>
<td style="text-align: left;">POLYGON ((110.2624 28.21778…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zhongfang</td>
<td style="text-align: right;">82884</td>
<td style="text-align: right;">113730</td>
<td style="text-align: left;">POLYGON ((109.9431 27.72858…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Huitong</td>
<td style="text-align: right;">74668</td>
<td style="text-align: right;">89002</td>
<td style="text-align: left;">POLYGON ((109.9419 27.10512…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jingzhou</td>
<td style="text-align: right;">43184</td>
<td style="text-align: right;">63532</td>
<td style="text-align: left;">POLYGON ((109.8186 26.75842…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mayang</td>
<td style="text-align: right;">99244</td>
<td style="text-align: right;">112988</td>
<td style="text-align: left;">POLYGON ((109.795 27.98008,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tongdao</td>
<td style="text-align: right;">46549</td>
<td style="text-align: right;">59330</td>
<td style="text-align: left;">POLYGON ((109.9294 26.46561…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xinhuang</td>
<td style="text-align: right;">20518</td>
<td style="text-align: right;">35930</td>
<td style="text-align: left;">POLYGON ((109.227 27.43733,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xupu</td>
<td style="text-align: right;">140576</td>
<td style="text-align: right;">154439</td>
<td style="text-align: left;">POLYGON ((110.7189 28.30485…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yuanling</td>
<td style="text-align: right;">121601</td>
<td style="text-align: right;">145795</td>
<td style="text-align: left;">POLYGON ((110.9652 28.99895…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zhijiang</td>
<td style="text-align: right;">92069</td>
<td style="text-align: right;">112587</td>
<td style="text-align: left;">POLYGON ((109.8818 27.60661…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lengshuijiang</td>
<td style="text-align: right;">43258</td>
<td style="text-align: right;">107515</td>
<td style="text-align: left;">POLYGON ((111.5307 27.81472…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shuangfeng</td>
<td style="text-align: right;">144567</td>
<td style="text-align: right;">162322</td>
<td style="text-align: left;">POLYGON ((112.263 27.70421,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xinhua</td>
<td style="text-align: right;">132119</td>
<td style="text-align: right;">145517</td>
<td style="text-align: left;">POLYGON ((111.3345 28.19642…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chengbu</td>
<td style="text-align: right;">51694</td>
<td style="text-align: right;">61826</td>
<td style="text-align: left;">POLYGON ((110.4455 26.69317…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dongan</td>
<td style="text-align: right;">59024</td>
<td style="text-align: right;">79925</td>
<td style="text-align: left;">POLYGON ((111.4531 26.86812…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dongkou</td>
<td style="text-align: right;">69349</td>
<td style="text-align: right;">82589</td>
<td style="text-align: left;">POLYGON ((110.6622 27.37305…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Longhui</td>
<td style="text-align: right;">73780</td>
<td style="text-align: right;">83352</td>
<td style="text-align: left;">POLYGON ((110.985 27.65983,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shaodong</td>
<td style="text-align: right;">94651</td>
<td style="text-align: right;">119897</td>
<td style="text-align: left;">POLYGON ((111.9054 27.40254…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Suining</td>
<td style="text-align: right;">100680</td>
<td style="text-align: right;">116749</td>
<td style="text-align: left;">POLYGON ((110.389 27.10006,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wugang</td>
<td style="text-align: right;">69398</td>
<td style="text-align: right;">81510</td>
<td style="text-align: left;">POLYGON ((110.9878 27.03345…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xinning</td>
<td style="text-align: right;">52798</td>
<td style="text-align: right;">63530</td>
<td style="text-align: left;">POLYGON ((111.0736 26.84627…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xinshao</td>
<td style="text-align: right;">140472</td>
<td style="text-align: right;">151986</td>
<td style="text-align: left;">POLYGON ((111.6013 27.58275…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shaoshan</td>
<td style="text-align: right;">118623</td>
<td style="text-align: right;">174193</td>
<td style="text-align: left;">POLYGON ((112.5391 27.97742…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xiangxiang</td>
<td style="text-align: right;">180933</td>
<td style="text-align: right;">210294</td>
<td style="text-align: left;">POLYGON ((112.4549 28.05783…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Baojing</td>
<td style="text-align: right;">82798</td>
<td style="text-align: right;">97361</td>
<td style="text-align: left;">POLYGON ((109.7015 28.82844…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fenghuang</td>
<td style="text-align: right;">83090</td>
<td style="text-align: right;">96472</td>
<td style="text-align: left;">POLYGON ((109.5239 28.19206…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Guzhang</td>
<td style="text-align: right;">97356</td>
<td style="text-align: right;">108936</td>
<td style="text-align: left;">POLYGON ((109.8968 28.74034…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Huayuan</td>
<td style="text-align: right;">59482</td>
<td style="text-align: right;">79819</td>
<td style="text-align: left;">POLYGON ((109.5647 28.61712…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jishou</td>
<td style="text-align: right;">77334</td>
<td style="text-align: right;">108871</td>
<td style="text-align: left;">POLYGON ((109.8375 28.4696,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Longshan</td>
<td style="text-align: right;">38777</td>
<td style="text-align: right;">48531</td>
<td style="text-align: left;">POLYGON ((109.6337 29.62521…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Luxi</td>
<td style="text-align: right;">111463</td>
<td style="text-align: right;">128935</td>
<td style="text-align: left;">POLYGON ((110.1067 28.41835…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yongshun</td>
<td style="text-align: right;">74715</td>
<td style="text-align: right;">84305</td>
<td style="text-align: left;">POLYGON ((110.0003 29.29499…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anhua</td>
<td style="text-align: right;">174391</td>
<td style="text-align: right;">188958</td>
<td style="text-align: left;">POLYGON ((111.6034 28.63716…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nan</td>
<td style="text-align: right;">150558</td>
<td style="text-align: right;">171869</td>
<td style="text-align: left;">POLYGON ((112.3232 29.46074…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yuanjiang</td>
<td style="text-align: right;">122144</td>
<td style="text-align: right;">148402</td>
<td style="text-align: left;">POLYGON ((112.4391 29.1791,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jianghua</td>
<td style="text-align: right;">68012</td>
<td style="text-align: right;">83813</td>
<td style="text-align: left;">POLYGON ((111.6461 25.29661…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lanshan</td>
<td style="text-align: right;">84575</td>
<td style="text-align: right;">104663</td>
<td style="text-align: left;">POLYGON ((112.2286 25.61123…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ningyuan</td>
<td style="text-align: right;">143045</td>
<td style="text-align: right;">155742</td>
<td style="text-align: left;">POLYGON ((112.0715 26.09892…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shuangpai</td>
<td style="text-align: right;">51394</td>
<td style="text-align: right;">73336</td>
<td style="text-align: left;">POLYGON ((111.8864 26.11957…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xintian</td>
<td style="text-align: right;">98279</td>
<td style="text-align: right;">112705</td>
<td style="text-align: left;">POLYGON ((112.2578 26.0796,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Huarong</td>
<td style="text-align: right;">47671</td>
<td style="text-align: right;">78084</td>
<td style="text-align: left;">POLYGON ((112.9242 29.69134…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Linxiang</td>
<td style="text-align: right;">26360</td>
<td style="text-align: right;">58257</td>
<td style="text-align: left;">POLYGON ((113.5502 29.67418…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Miluo</td>
<td style="text-align: right;">236917</td>
<td style="text-align: right;">279414</td>
<td style="text-align: left;">POLYGON ((112.9902 29.02139…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pingjiang</td>
<td style="text-align: right;">220631</td>
<td style="text-align: right;">237883</td>
<td style="text-align: left;">POLYGON ((113.8436 29.06152…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xiangyin</td>
<td style="text-align: right;">185290</td>
<td style="text-align: right;">219273</td>
<td style="text-align: left;">POLYGON ((112.9173 28.98264…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cili</td>
<td style="text-align: right;">64640</td>
<td style="text-align: right;">83354</td>
<td style="text-align: left;">POLYGON ((110.8822 29.69017…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chaling</td>
<td style="text-align: right;">70046</td>
<td style="text-align: right;">90124</td>
<td style="text-align: left;">POLYGON ((113.7666 27.10573…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Liling</td>
<td style="text-align: right;">126971</td>
<td style="text-align: right;">168462</td>
<td style="text-align: left;">POLYGON ((113.5673 27.94346…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yanling</td>
<td style="text-align: right;">144693</td>
<td style="text-align: right;">165714</td>
<td style="text-align: left;">POLYGON ((113.9292 26.6154,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">You</td>
<td style="text-align: right;">129404</td>
<td style="text-align: right;">165668</td>
<td style="text-align: left;">POLYGON ((113.5879 27.41324…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zhuzhou</td>
<td style="text-align: right;">284074</td>
<td style="text-align: right;">311663</td>
<td style="text-align: left;">POLYGON ((113.2493 28.02411…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sangzhi</td>
<td style="text-align: right;">112268</td>
<td style="text-align: right;">126892</td>
<td style="text-align: left;">POLYGON ((110.556 29.40543,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yueyang</td>
<td style="text-align: right;">203611</td>
<td style="text-align: right;">229971</td>
<td style="text-align: left;">POLYGON ((113.343 29.61064,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Qiyang</td>
<td style="text-align: right;">145238</td>
<td style="text-align: right;">165876</td>
<td style="text-align: left;">POLYGON ((111.5563 26.81318…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Taojiang</td>
<td style="text-align: right;">251536</td>
<td style="text-align: right;">271045</td>
<td style="text-align: left;">POLYGON ((112.0508 28.67265…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shaoyang</td>
<td style="text-align: right;">108078</td>
<td style="text-align: right;">117731</td>
<td style="text-align: left;">POLYGON ((111.5013 27.30207…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lianyuan</td>
<td style="text-align: right;">238300</td>
<td style="text-align: right;">256646</td>
<td style="text-align: left;">POLYGON ((111.6789 28.02946…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hongjiang</td>
<td style="text-align: right;">108870</td>
<td style="text-align: right;">126603</td>
<td style="text-align: left;">POLYGON ((110.1441 27.47513…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hengyang</td>
<td style="text-align: right;">108085</td>
<td style="text-align: right;">127467</td>
<td style="text-align: left;">POLYGON ((112.7144 26.98613…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Guiyang</td>
<td style="text-align: right;">262835</td>
<td style="text-align: right;">295688</td>
<td style="text-align: left;">POLYGON ((113.0811 26.04963…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Changsha</td>
<td style="text-align: right;">248182</td>
<td style="text-align: right;">336838</td>
<td style="text-align: left;">POLYGON ((112.9421 28.03722…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Taoyuan</td>
<td style="text-align: right;">244850</td>
<td style="text-align: right;">267729</td>
<td style="text-align: left;">POLYGON ((112.0612 29.32855…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xiangtan</td>
<td style="text-align: right;">404456</td>
<td style="text-align: right;">431516</td>
<td style="text-align: left;">POLYGON ((113.0426 27.8942,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dao</td>
<td style="text-align: right;">67608</td>
<td style="text-align: right;">85667</td>
<td style="text-align: left;">POLYGON ((111.498 25.81679,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jiangyong</td>
<td style="text-align: right;">33860</td>
<td style="text-align: right;">51028</td>
<td style="text-align: left;">POLYGON ((111.3659 25.39472…</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li><p><strong><code>lag.listw(b_weights2, hunan$GDPPC)</code></strong>: This calculates the <strong>spatial window sum</strong> of the GDPPC values using the binary weights matrix (<code>b_weights2</code>). Each region’s GDPPC value and its neighbors’ GDPPC values are summed up directly.</p></li>
<li><p><strong><code>w_sum_gdppc</code></strong>: Stores the list of region names (<code>hunan$NAME_3</code>) along with the spatial window sum of GDPPC values for each region.</p></li>
</ul>
</section>
<section id="visualise-and-interpret-the-results" class="level3">
<h3 class="anchored" data-anchor-id="visualise-and-interpret-the-results">8.4.4 visualise and interpret the results</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>w_sum_gdppc <span class="ot">&lt;-</span> <span class="fu">qtm</span>(hunan, <span class="st">"w_sum GDPPC"</span>)</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(lag_sum_gdppc, w_sum_gdppc, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands_On_Exercise5_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><strong>Spatial Window Sum</strong>: This method calculates the sum of neighboring values without normalizing by the number of neighbors (i.e., without row-standardization). Each region’s value is added together with its neighbors’ values, including itself.</p></li>
<li><p><strong>Code Breakdown</strong>:</p>
<ul>
<li><p>First, the diagonal (self) element is added to the neighbor list using <code>include.self()</code>.</p></li>
<li><p><strong>Binary weights</strong> (1 for each neighbor, including self) are applied to compute the spatial window sum using the <code>lag.listw()</code> function.</p></li>
<li><p>The spatial window sum is then visualized alongside the row-standardized spatial lag to compare the two approaches.</p></li>
</ul></li>
<li><p><strong>Comparison</strong>: The spatial window sum gives a <strong>total</strong> influence of neighbors, whereas row-standardized weights give an <strong>average</strong> influence. Both approaches offer different insights into the spatial relationships between regions.</p></li>
<li></li>
</ul>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>